---
- platform: rflink
  devices:
    newkaku_0114ef92_b: {}
    newkaku_0114ef92_c: {}
    newkaku_011fdd46_b: {}
    newkaku_011fdd46_c: {}
    newkaku_01616a32_a: {}
    newkaku_014ad3ba_a: {}
    newkaku_011fad02_c: {}
    newkaku_011fad02_b: {}
    newkaku_01074522_a: {}
    newkaku_014e5906_a: {}
    newkaku_016138ba_a: {}

- platform: mqtt
  command_topic: "home-assistant/kaylearning/switch"
  state_topic: "home-assistant/kaylearning/switch"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  name: "Kay Learning"

- platform: mqtt
  command_topic: "home-assistant/hallway/switch"
  state_topic: "home-assistant/hallway/switch"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  name: "Hallway"

- platform: mqtt
  command_topic: "home-assistant/toilet/switch"
  state_topic: "home-assistant/toilet/switch"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  name: "Toilet"

#- platform: mqtt
#  command_topic: "home-assistant/kitchen/switch/sink"
#  state_topic: "home-assistant/kitchen/switch/sink"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Kitchen Sink"

#- platform: mqtt
#  command_topic: "home-assistant/kitchen/switch/seeling"
#  state_topic: "home-assistant/kitchen/switch/seeling"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Kitchen Seeling"

#- platform: mqtt
#  command_topic: "home-assistant/bedroom/switch"
#  state_topic: "home-assistant/bedroom/switch"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Bedroom"

#- platform: mqtt
#  command_topic: "home-assistant/bathroom/switch"
#  state_topic: "home-assistant/bathroom/switch"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Bathroom"

#- platform: mqtt
#  command_topic: "home-assistant/diningroom/switch"
#  state_topic: "home-assistant/diningroom/switch"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Diningroom"

#- platform: mqtt
#  command_topic: "home-assistant/balcony/switch"
#  state_topic: "home-assistant/balcony/switch"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Balcony"

#- platform: mqtt
#  command_topic: "home-assistant/livingroom/switch"
#  state_topic: "home-assistant/livingroom/switch"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  name: "MQTT Livingroom"

- platform: template
  switches:
    # DOMOTICZ
    domoticz:
      friendly_name: Domoticz
      value_template: "{{ is_state_attr('remote.logitech_harmony', 'current_activity', 'Domoticz') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'Domoticz'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'PowerOff'

    # ZIGGO
    tv:
      friendly_name: TV
      value_template: "{{ is_state_attr('remote.logitech_harmony', 'current_activity', 'Ziggo') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'Ziggo'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'PowerOff'

    # AppleTV
    appletv:
      friendly_name: AppleTV
      value_template: "{{ is_state_attr('remote.logitech_harmony', 'current_activity', 'AppleTV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'AppleTV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'PowerOff'

    # AirPlay
    airplay:
      friendly_name: AirPlay
      value_template: "{{ is_state_attr('remote.logitech_harmony', 'current_activity', 'AirPlay') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'AirPlay'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'PowerOff'

    # Kodi
    kodi:
      friendly_name: Kodi
      value_template: "{{ is_state_attr('remote.logitech_harmony', 'current_activity', 'Kodi') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'Kodi'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'PowerOff' 

    # IPTV
    iptv:
      friendly_name: IPTV
      value_template: "{{ is_state_attr('remote.logitech_harmony', 'current_activity', 'IPTV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'IPTV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.logitech_harmony
          activity: 'PowerOff'

