###########################################################################################
#
# KODI CONTROL LIGHTS RUN SCRIPT BASED ON STATUS
#
###########################################################################################

- alias: "Control - Kodi Status"
  trigger:

    platform: state
    entity_id: media_player.kodi

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: switch.mqtt_scene_kodi
      state: "on"

  action:
    - service: script.turn_off
      entity_id:
        - script.kodi_control_playing
        - script.kodi_control_paused
        - script.kodi_control_idle

    - delay: "00:00:02"

    - service_template: >-
        {% if states('media_player.kodi') == 'playing' %} script.kodi_control_playing
        {% elif states('media_player.kodi') == 'paused' %} script.kodi_control_paused
        {% else %} script.kodi_control_idle
        {% endif %}
