###########################################################################################
#
# BATHROOM CONTROL LIGHTS BASED ON SENSOR IS OFF 5MIN
#
###########################################################################################

- alias: "Control - Bathroom Lights Are On"
  trigger:

    platform: state
    entity_id: binary_sensor.node_15 # Motion Bathroom
    to: "off"
    for:
      minutes: 2

  action:
    - service: switch.turn_off
      entity_id: switch.meek_bathroom

    - service_template: "{{ 'fan.turn_on' if is_state('binary_sensor.node_16', 'on') else 'fan.turn_off' }}"
      entity_id: fan.afzuiging_badkamer

    - service: script.pushover_engine
      data_template:
        message: "Nobody in bathroom for 3 minutes. Turned off bathroom switch and light"
        priority: 0
        sound: bike
        title: "HA System"
