####################################################
#
# SMTP EMAIL
#
# https://www.home-assistant.io/integrations/smtp/
#
####################################################
---
name: "HA Email"
platform: smtp
server: vps.oudenes.photography
port: 587
timeout: 15
sender: !secret root_email_username
encryption: starttls
username: !secret root_email_username
password: !secret root_email_password
recipient:
  - info@oudenes.photography
  - root@oudenes.photography
sender_name: HA Notify
