###########################################################################################
#
# PUSHOVER
#
# https://www.home-assistant.io/integrations/pushover/
#
###########################################################################################
---
name: "Pushover"
platform: pushover
api_key: !secret notify_apikey
user_key: !secret notify_userkey
