- alias: Motion Detection - Diningroom On
  trigger:
    platform: state
    entity_id: binary_sensor.node_18
    to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'on'

  action:
    service: light.turn_on
    entity_id: light.dressoir_all
    data:
      kelvin: 2700
      brightness_pct: 20

- alias: Motion Detection - Diningroom Off
  trigger:
    platform: state
    entity_id: binary_sensor.node_18
    to: 'off'

  condition:                                                                                               
    - condition: state                                                                                     
      entity_id: input_boolean.scene_goodnight                                                             
      state: 'on'

  action:
    service: light.turn_off
    entity_id: light.dressoir_all
