- alias: Motion Detection - Livingroom On
  trigger:
    platform: state
    entity_id: binary_sensor.node_19
    to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'on'

    - condition: state
      entity_id: light.livingroom_wall
      state: 'off'

    - condition: state
      entity_id: light.livingroom_window
      state: 'off' 

    - condition: state
      entity_id: light.livingroom_all
      state: 'off'

  action:
    service: light.turn_on
    data:
      entity_id: light.livingroom_all
      kelvin: 2700
      brightness_pct: 20

- alias: Motion Detection - Livingroom Off
  trigger:
    platform: state
    entity_id: binary_sensor.node_19
    to: 'off'

  condition:                                                                                               
    - condition: state                                                                                     
      entity_id: input_boolean.scene_goodnight                                                             
      state: 'on'

    - condition: state
      entity_id: switch.newkaku_0114ef92_b
      state: 'off'

    - condition: state
      entity_id: switch.newkaku_0114ef92_c
      state: 'off'

  action:
    service: light.turn_off
    entity_id: light.livingroom_all
