- alias: 'Motion Detection - Toilet On'
  trigger:
    platform: state
    entity_id: binary_sensor.node_20
    to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'on'

  action:
    service: light.turn_on
    entity_id: light.toilet_all
    data:
      brightness_pct: 20
      kelvin: 4700

- alias: 'Motion Detection - Toilet Off'
  trigger:
    platform: state
    entity_id: binary_sensor.node_20
    to: 'off'

  condition:                                                                                               
    - condition: state                                                                                     
      entity_id: input_boolean.scene_goodnight                                                             
      state: 'on'

  action:
    service: light.turn_off
    entity_id: light.toilet_all
