###########################################################################################
#
# LIVINGROOM CONTROL LIGHT BASED ON SENSOR AND SCENE GOODNIGHT
#
###########################################################################################

- alias: "Motion Detection - Livingroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_19

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "on"

    - condition: state
      entity_id: switch.newkaku_0114ef92_b
      state: "off"

    - condition: state
      entity_id: switch.newkaku_0114ef92_c
      state: "off"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.livingroom_all
      #kelvin: 2800
      brightness_pct: "{{ 20 if is_state('binary_sensor.node_19', 'on') else 0 }}"
