###########################################################################################
#
# KITCHEN CONTROL LIGHTS BASED ON SENSOR STATUS AND EVENT
#
###########################################################################################

- alias: "Control - Lux Control Kitchen"
  trigger:

    platform: state
    entity_id: switch.mqtt_lux_level_low

  condition:
    - condition: state
      entity_id: switch.meek_kitchen_seeling
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_daytime
      state: "on"

  action:
    service: light.turn_on
    data_template:
      entity_id:
        - light.kitchen_all
        - light.seeling_all
      #kelvin: 2800
      brightness_pct: >-
        {% if (states.switch.mqtt_lux_level_low.state) == 'on' %} 100
        {% else %} 0
        {% endif %}
