- alias: "Motion Detection - Diningroom On Off"
  trigger:
    platform: state
    entity_id: binary_sensor.node_18

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: "on"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.dressoir_all
      kelvin: 4700
      brightness_pct: "{{ 20 if is_state('binary_sensor.node_18', 'on') else 0 }}"
