- alias: 'Control - Bathroom Lights Are On'
  trigger:
  - entity_id: binary_sensor.node_15
    platform: state
    to: 'off'
    for:
      minutes: 2

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off'

    - condition: state
      entity_id: switch.newkaku_01074522_a
      state: 'on'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.bathroom
      
    - service: script.pushover_engine
      data_template:
        message: "Nobody in bathroom for 5 minutes. Turned off bathroom switch and light"
        priority: 0
        sound: bike
        title: "HA System"
