- alias: "Control - Bedroom Lights Are On"
  trigger:
  - entity_id: binary_sensor.node_14
    platform: state
    to: "off"
    for:
      minutes: 5

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.newkaku_01074522_a
      state: "on"

  action:
    - service: switch.turn_off
      entity_id: switch.newkaku_01074522_a 

    - service: script.pushover_engine
      data_template:
        message: "Nobody in bedroom for 5 minutes. Turned off bedroom switch and light" 
        priority: 0
        sound: bike
        title: "HA System"
