- alias: 'Motion Detection - Kitchen On Off'
  trigger:
    platform: state
    entity_id: binary_sensor.node_16

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'off'

  action: 
    - service_template: >-
        {% if (states.sensor.holiday.state) == 'Christmas' and (states.input_boolean.scene_goodnight.state) == 'off' %} script.kitchen_christmas_turn_on
        {% elif (states.sensor.holiday.state) == 'Halloween' and (states.input_boolean.scene_goodnight.state) == 'off' %} script.kitchen_halloween_turn_on
        {% elif (states.sensor.holiday.state) == 'Kingsday' and (states.input_boolean.scene_goodnight.state) == 'off' %} script.kitchen_kingsday_turn_on
        {% elif (states.sensor.holiday.state) == 'Birthday' and (states.input_boolean.scene_goodnight.state) == 'off' %} script.kitchen_birthday_turn_on
        {% else %} script.kitchen_normal_turn_on
        {% endif %}

    - service_template: >-
          {% if (states.binary_sensor.node_16.state) == 'on' %} shell_command.meek_kitchen_sensor_on
          {% else %} shell_command.meek_kitchen_sensor_off
          {% endif %}