####################################################
#
# APPLETV CONTROL LIGHTS RUN SCRIPT BASTED ON STATUS
#
####################################################

- alias: "Control - AppleTV Status"
  trigger:

    platform: state
    entity_id: media_player.woonkamer_2

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: input_boolean.scene_appletv
      state: "on"

    - condition: template
      value_template: >
        {{ trigger.from_state is none or
           trigger.to_state is not none and
           trigger.to_state.state != trigger.from_state.state }}

  action:
    - service: script.turn_off
      entity_id:
        - script.appletv_control_playing
        - script.appletv_control_paused
        - script.appletv_control_idle

    - delay: "00:00:02"

    - service_template: >-
        {% if (states.media_player.woonkamer_2.state) == 'playing' %} script.appletv_control_playing
        {% elif (states.media_player.woonkamer_2.state) == 'paused' %} script.appletv_control_paused
        {% else %} script.appletv_control_idle
        {% endif %}
