###########################################################################################
#
# BATHROOM CONTROL LIGHTS BASED ON SENSOR IS OFF 5MIN
#
###########################################################################################

- alias: "Control - Bathroom Lights Are On"
  trigger:

    platform: state
    entity_id: binary_sensor.node_15
    to: "off"
    for:
      minutes: 2

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.newkaku_01616a32_a
      state: "on"

  action:
    - service: switch.turn_off
      entity_id: switch.newkaku_01616a32_a

    - service: fan.turn_off
      entity_id: fan.afzuiging_badkamer

    - service: script.pushover_engine
      data_template:
        message: "Nobody in bathroom for 5 minutes. Turned off bathroom switch and light"
        priority: 0
        sound: bike
        title: "HA System"
