- alias: 'Control - ITHO fan off when goes to standby'
  trigger:
    platform: state
    entity_id: sensor.itho_speed

  condition:
    - condition: state
      entity_id: sensor.itho_speed
      state: 'Laag'

  action:
    - service: fan.turn_off
      entity_id: fan.afzuiging_badkamer
