###########################################################################################
#
# BATHROOM CONTROL LIGHTS BASED ON SCENE GOODNIGHT
#
###########################################################################################

- alias: "Motion Detection - Bathroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_15

  condition:
    condition: state
    entity_id: switch.meek_bathroom
    state: "off"

  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom_all
#        kelvin: 2800
        brightness_pct: >-
          {% if (states.binary_sensor.node_15.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'on' %} 50
          {% elif (states.binary_sensor.node_15.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} 100
          {% else %} 0
          {% endif %}

    - service: mqtt.publish
      data:
        topic: 'homeassistant/bedroom/controlha'
        payload: 1

    - service_template: >-
        {% if (states.binary_sensor.node_15.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} switch.turn_on
        {% elif (states.binary_sensor.node_15.state) == 'off' and (states.switch.mqtt_scene_goodnight.state) == 'off' %}  switch.turn_off
        {% endif %}
      entity_id: switch.meek_bathroom
