- alias: "Control - Lux on Daytime Low"
  trigger:
    - platform: numeric_state
      entity_id: sensor.node_19_luminance
      below: 160

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: "on"
  
    - condition: state
      entity_id: input_boolean.lux_level_low
      state: "off"

    - condition: state 
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

  action:
    - service: light.turn_on
      entity_id:
        - light.livingroom_all
        - light.dressoir_all
      data:
        transition: 10 
        brightness_pct: 75

    - service: input_boolean.turn_on
      entity_id: input_boolean.lux_level_low

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_lux_evening_on: "true"

- alias: 'Control - Lux on Daytime Normal'
  trigger:
    - platform: numeric_state
      entity_id: sensor.node_19_luminance
      above: 150

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: "on"

    - condition: state
      entity_id: input_boolean.lux_level_low
      state: "on"

    - condition: state 
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

  action:
    - service: light.turn_on
      entity_id:
        - light.livingroom_all
        - light.dressoir_all
      data:
        transition: 10
        brightness_pct: 0

    - service: input_boolean.turn_off
      entity_id: input_boolean.lux_level_low

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_lux_evening_off: "true"
