- alias: 'Control - Kodi Status'
  trigger:
  - entity_id: media_player.kodi
    platform: state

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'  

    - condition: state
      entity_id: input_boolean.scene_kodi
      state: 'on' 

  action:
    - service_template: >-
        {% if (states.media_player.kodi.state) == 'playing' %} script.kodi_control_playing
        {% elif (states.media_player.kodi.state) == 'paused' %} script.kodi_control_paused
        {% else %} script.kodi_control_idle
        {% endif %}
