- alias: "Control - AppleTV is playing"
  trigger:
    platform: state
    entity_id: media_player.woonkamer_2
    to: "playing"
    for:
      seconds: 10

  condition: 
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: input_boolean.scene_appletv
      state: "on"

  action:
    - service: light.turn_on
      data:
        entity_id: light.livingroom_wall
        brightness_pct: 60

    - service: light.turn_on
      data:
        entity_id: 
          - light.livingroom_window
          - light.nanoleaf
          - light.balcony
        brightness_pct: 30

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_all
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 25 }}"

    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
