- alias: 'Control - Disable Nest Control'
  trigger:

  - entity_id: input_boolean.nest_disable_control
    platform: state

  action:
    - service: script.pushover_engine
      data_template:
        message: >-
          {% if (states.input_boolean.nest_disable_control.state) == 'on' %} "Automation Nest Control is disabled"
          {% else %} "Automation Nest Control is enabled"
          {% endif %}
        priority: 0
        sound: bike
        title: "HA Scene System"

    - service_template: >-
        {% if (states.input_boolean.nest_disable_control.state) == 'on' %} automation.turn_off
        {% else %} automation.turn_on
        {% endif %}
      entity_id:
        - automation.control_nest_control_goodnight_scene
        - automation.control_nest_control_nobody_home
        - automation.control_nest_control_someone_home
