- alias: 'Control - Nest Control Someone Home'
  trigger:
  - platform: state
    entity_id: binary_sensor.sensor_manual_family_home
    to: 'on'

  - platform: state
    entity_id: climate.entryway

  condition:
    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: 'on' 

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off'

  action:
    - service: climate.set_temperature
      entity_id: climate.entryway
      data_template:
        temperature: >-
          {% set outside = states('sensor.dark_sky_temperature') | float %}
          {% set inside = states('sensor.entryway_thermostat_target') | float %}
          {% if outside >= 12 and inside >= 8 %} 10
          {% elif outside <= 12 and inside <= 9 %} 18
          {% else %} 9
          {% endif %}
