###########################################################################################
#
# CONTROL BEDROOM LIGHTS WHEN DOOR SENSOR IS ON OR OFF
#
###########################################################################################

- alias: "Door Sensor - Bedroom Door Open Close"
  trigger:

    platform: state
    entity_id: binary_sensor.node_12

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: light.bedroom_all
      state: "on"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      kelvin: 2800
      brightness_pct: >- #"{{ 20 if is_state('binary_sensor.node_12', 'on') else 100 }}"

        {% if (states.binary_sensor.node_12.state) == 'on' and ((states.season.season.state) == 'Spring' or (states.season.season.state) == 'Summer') %} 20

        {% elif (states.binary_sensor.node_12.state) == 'on' and ((states.season.season.state) == 'Autumn' or (states.season.season.state) == 'Winter') %} 100

        {% else %} 0
        {% endif %}
