- alias: 'Door Sensor - Diningroom door open Diningroom light off'
  trigger:
    platform: state
    entity_id: binary_sensor.node_10

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'off'

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off' 

  action:
    - service: light.turn_on
      entity_id: light.dressoir_all
      data_template:
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: homeassistant.turn_on
      entity_id: light.newkaku_01401eb6_a
      data_template:
        brightness_pct: >-
          {% if (states.binary_sensor.node_10.state) == 'on' and
                (states.switch.kay_learning.state) == 'off' and
                ((states.sensor.season.state) == 'spring' or
                 (states.sensor.season.state) == 'summer') %}
                  0

          {% elif (states.binary_sensor.node_10.state) == 'off' and
                  (states.switch.kay_learning.state) == 'off' and
                  ((states.sensor.season.state) == 'spring' or
                   (states.sensor.season.state) == 'summer') %}
                    50

          {% elif (states.binary_sensor.node_10.state) == 'on' and
                  (states.switch.kay_learning.state) == 'on' %}
                  100

          {% elif (states.binary_sensor.node_10.state) == 'off' and
                  (states.switch.kay_learning.state) == 'on' %}
                  100

          {% else %} 50
          {% endif %}
