- alias: "Control - Nest Control Nobody Home"
  trigger:
  - platform: state
    entity_id: binary_sensor.sensor_manual_family_home
    to: "off"

  - platform: state
    entity_id: climate.entryway

  condition:
    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "off" 

  action:
    - service: climate.set_temperature
      entity_id: climate.entryway
      data_template:
        temperature: >-
          {% set inside = states('sensor.entryway_thermostat_target') | float %}
          {% if inside > 11 %} 9
          {% else %} 9
          {% endif %}
