- alias: 'Control - Disable Nest Control'
  trigger:

  - entity_id: input_boolean.nest_disable_control
    platform: state

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ 'Automation Nest Control is disabled' if is_state('input_boolean.nest_disable_control', 'on') else 'Automation Nest Control is enable' }}"
        priority: 0
        sound: bike
        title: "HA Scene System"

    - service_template: "{{ 'automation.turn_off' if is_state('input_boolean.nest_disable_control', 'on') else 'automation.turn_on' }}"
      entity_id:
        - automation.control_nest_control_goodnight_scene
        - automation.control_nest_control_nobody_home
        - automation.control_nest_control_someone_home
