- alias: "Control - Turn On Off Zwave 5 6 7"
  trigger:
    - entity_id: binary_sensor.sensor_manual_family_home
      platform: state

  action:
    - service_template: "{{ 'switch.turn_on' if is_state('binary_sensor.sensor_manual_family_home', 'on') else 'switch.turn_off' }}"
      data:
        entity_id:
          - switch.node_5_switch
          - switch.node_6_switch
          - switch.node_7_switch