###########################################################################################
#
# TOILET CONTROL LIGHT BASED ON SENSOR AND SCENE GOODNIGHT
#
###########################################################################################

- alias: "Motion Detection - Toilet On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_20

  condition:
    condition: state
    entity_id: switch.mqtt_scene_goodnight
    state: "on"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.toilet_all
      #kelvin: 2800
      brightness_pct: "{{ 20 if is_state('binary_sensor.node_20', 'on') else 0 }}"
