- alias: 'Motion Detection - Hallway On Off'
  trigger:
    platform: state
    entity_id: binary_sensor.node_17

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'on'

  action:
    service: light.turn_on
    entity_id: light.hallway
    data_template:
      kelvin: 2700
      brightness_pct: >-
        {% if (states.binary_sensor.node_17.state) == 'on' %} 20
        {% else %} 0
        {% endif %}
