---
host: !secret ip_cam_host
port: !secret ip_cam_port
username: !secret ip_cam_user
password: !secret ip_cam_pass

motion_sensor: true
sensors:
  - motion
switches:
  - exposure_lock
  - ffc
  - focus
  - gps_active
  - night_vision
  - overlay
  - torch
  - whitebalance_lock
  - video_recording
