---
host: 192.168.100.9
port: 8080
scan_interval: 5
motion_sensor: true
sensors:
  - motion
switches:
  - exposure_lock
  - ffc
  - focus
  - gps_active
  - night_vision
  - overlay
  - torch
  - whitebalance_lock
  - video_recording
