####################################################
#
# NMAP_TRACKER
#
# https://www.home-assistant.io/integrations/nmap_tracker/
#
####################################################
---
platform: nmap_tracker
hosts: 192.168.100.0/24
home_interval: 1
