####################################################
#
# GOOGLE
#
# http UNKNOWN
#
####################################################
---
client_id: !secret google_client
client_secret: !secret google_secret
