###########################################################################################
#
# HISTORY
#
# https://www.home-assistant.io/integrations/history/
#
###########################################################################################
---
include:
  entities:
    - device_tracker.geofency_kay
    - device_tracker.e7b5aad4_fc4c_4ee8_98fd_2337da788a0f
    - device_tracker.geofency_peter
    - device_tracker.1717fe36_3c70_4599_963c_b70b6ee95eba
    - light.bathroom_all
    - light.bedroom_all
    - light.hallway
    - light.balcony
    - light.toilet_all
    - light.livingroom_all
    - light.kitchen_all
    - light.sink_all
    - binary_sensor.node_14
    - binary_sensor.node_15
    - binary_sensor.node_16
    - binary_sensor.node_17
    - binary_sensor.node_18
    - binary_sensor.node_19
    - binary_sensor.node_20
    - binary_sensor.node_21
    - binary_sensor.node_12
    - sensor.fibaro_frontdoor_custom_sensor
