####################################################
#
# LOGGER
#
# https://www.home-assistant.io/integrations/logger/
#
####################################################
---
default: error
logs:
  homeassistant.components.websocket_api: info
  homeassistant.components.zwave: info
  homeassistant.helpers.service: debug
  homeassistant.components.pushover.notify: debug

#  pyatv: debug
