---
default: error
logs:
  homeassistant.components.websocket_api: error
  homeassistant.components.zwave: info
  homeassistant.helpers.service: debug
  homeassistant.components.pushover.notify: debug
  
#  pyatv: debug
