###########################################################################################
#
# LOGGER
#
# https://www.home-assistant.io/integrations/logger/
#
###########################################################################################
---
default: error
logs:
  homeassistant.components.websocket_api: warning
  homeassistant.components.zwave: warning
  homeassistant.helpers.service: warning
  homeassistant.components.pushover.notify: warning
  homeassistant.loader: warning
  homeassistant.components.alexa.state_report: fatal

#  pyatv: debug
