###########################################################################################
#
# RECORDER
#
# https://www.home-assistant.io/integrations/recorder/
#
###########################################################################################
---
db_url: !secret mariadb
purge_keep_days: 5
purge_interval: 1
include:
  domains:
    - sensor
    - binary_sensor
    - switch
    - automation
    - light
    - media_player
    - updater
  entities:
    - device_tracker.geofency_kay
    - device_tracker.e7b5aad4_fc4c_4ee8_98fd_2337da788a0f
    - device_tracker.geofency_peter
    - device_tracker.1717fe36_3c70_4599_963c_b70b6ee95eba
    - device_tracker.google_maps_108275535398702967599
    - device_tracker.google_maps_hassio_oudenes_gmail_com

exclude:
  entities:
    - sensor.power_consumption
    - sensor.voltage_phase_l1
