---
#db_url: !secret mariadb

purge_keep_days: 5
purge_interval: 1
exclude:
  domains:
    - automation
    - weblink
    - updater
    - script
    - zone
    - updater
  entities:
    - sun.sun
    - zone.home
    - sensor.batt_diningroomdoor
    - sensor.batt_frontdoor
    - sensor.batt_bedroomdoor
    - sensor.batt_motion_bedroom
    - sensor.batt_motion_bathroom
    - sensor.batt_motion_diningroom
    - sensor.batt_motion_hallway
    - sensor.batt_motion_kitchen
    - sensor.batt_motion_livingroom
    - sensor.node_2_energy
    - sensor.node_5_energy
    - sensor.node_6_energy
    - sensor.node_7_energy
    - sensor.node_8_energy
    - sensor.node_9_energy
    - sensor.node_14_luminance
    - sensor.node_15_luminance
    - sensor.node_16_luminance
    - sensor.node_17_luminance
    - sensor.node_18_luminance
    - sensor.node_19_luminance
    - sensor.node_20_luminance
    - switch.node_2_switch
    - switch.node_5_switch
    - switch.node_6_switch
    - switch.node_7_switch
    - switch.node_8_switch
    - switch.node_9_switch
