###########################################################################################
#
# RECORDER
#
# https://www.home-assistant.io/integrations/recorder/
#
###########################################################################################
---
db_url: !secret mariadb
purge_keep_days: 5
purge_interval: 1
include:
  domains:
    - sensor
    - binary_sensor
    - switch
    - automation
    - light
    - media_player
    - updater
  entities:
    - device_tracker.geofency_kay
    - device_tracker.e7b5aad4_fc4c_4ee8_98fd_2337da788a0f
    - device_tracker.geofency_peter
    - device_tracker.1717fe36_3c70_4599_963c_b70b6ee95eba
    - device_tracker.google_maps_108275535398702967599
    - device_tracker.google_maps_hassio_oudenes_gmail_com
    - switch.circadian_lighting_circadian_bedroom
    - switch.circadian_lighting_circadian_dressoir
    - switch.circadian_lighting_circadian_hallway
    - switch.circadian_lighting_circadian_kitchen
    - switch.circadian_lighting_circadian_livingroom
    - switch.circadian_lighting_circadian_toilet
    - switch.circadian_lighting_circadian_bathroom
    - switch.mqtt_scene_appletv
    - switch.mqtt_scene_cooking
    - switch.mqtt_scene_disco
    - switch.mqtt_scene_evening
    - switch.mqtt_scene_goodnight
    - switch.mqtt_scene_guests
    - switch.mqtt_scene_kodi
    - switch.mqtt_scene_tv
    - switch.mqtt_scene_daytime
    - switch.mqtt_scene_sexy
    - switch.mqtt_scene_sleeping

exclude:
  entities:
    - sensor.power_consumption
    - sensor.voltage_phase_l1
