- alias: 'Control - AppleTV is playing'
  trigger:
  - entity_id: media_player.woonkamer
    platform: state
    to: playing
    for:
      seconds: 10

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - condition: state
      entity_id: input_boolean.scene_appletv
      state: 'on'   

  action:
    - service: script.appletv_control_playing

- alias: 'Control - AppleTV is on pause or idle'
  trigger:
  - entity_id: media_player.woonkamer
    platform: state

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon' 

    - condition: state
      entity_id: input_boolean.scene_appletv
      state: 'on'
 
  action:
    - service_template: >-
        {% if (states.media_player.woonkamer.state) == 'paused' %} script.appletv_control_paused
        {% else %} script.appletv_control_idle
        {% endif %}
