- alias: 'System - Backup HA on Monday and Saterday'
  initial_state: true
  trigger:
    - platform: time
      at: '04:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - sat
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Full_Backup_{{ now().strftime('%Y%m%d') }} 

    - service: script.turn_on
      entity_id: script.pushover_engine
      data_template:
        variables: 
          message: "HASS backup has run. the snapshot name is ---->  Full_Backup_{{ now().strftime('%Y%m%d') }}"
          priority: 0
          sound: bike
          title: "HA System"
