- alias: 'Notification - Kay Left or Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_kay
    platform: state

  action:
  - service: notify.pushover
    data_template:
      message: >-
       {% if (states.device_tracker.geofency_kay.state) == 'home' %} Kay arrived home.
       {% else %} Kay left home.
       {% endif %}
      title: "HA System"
