- alias: 'Notification - Kay Left or Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_kay
    platform: state

  action:
    - service: script.turn_on
      entity_id: script.pushover_engine
      data_template:
        variables: 
          message: >-
            {% if (states.device_tracker.geofency_kay.state) == 'home' %} Kay arrived home. 
            {% else %} Kay left home.
            {% endif %} 
          priority: 0
          sound: bike
          title: "HA Notify Engine"
