- alias: 'Notification - Update Available Notification'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.update_available

  condition:
    - condition: template
      value_template: "{{ states('sensor.current_version') != states('sensor.latest_version') }}"

  action:
    service: notify.pushover
    data_template:
      message: "HA version {{ states('sensor.latest_version') }} is available!. {{now().strftime('%d-%m-%Y')}}"
      title: "HA System"
