- alias: 'Notification - Login Failure'
  hide_entity: False
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.http_login') != 'unknown' }}"

  action:
    - service: script.turn_on
      entity_id: script.pushover_engine
      data_template:
        variables: 
          message: "There is a bad login registered on Home Assistant"
          priority: 2
          sound: bike
          title: "HA Security ALERT"
