- alias: 'Notification - Peter Left or Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    platform: state

  action:
    - service: script.turn_on
      entity_id: script.pushover_engine
      data_template:
        variables: 
          message: >-
            {% if (states.device_tracker.geofency_peter.state) == 'home' %} Peter is thuis aangekomen.
            {% else %} Peter is van huis weg gegaan.
            {% endif %}
          priority: 0
          sound: bike
          title: "HA Notify Engine"
