- alias: 'Notification - Peter Left or Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    platform: state

  action:
  - service: notify.pushover
    data_template:
      message: >-
       {% if (states.device_tracker.geofency_peter.state) == 'home' %} Peter is thuis aangekomen.
       {% else %} Peter is van huis weg gegaan.
       {% endif %}
      title: "HA System"
