- alias: 'System - Start Automation after start HomeKit'
  hide_entity: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:00:10
    - service: homekit.start
    - delay: 00:00:30
    - service: automation.turn_on
      entity_id:
        - automation.notification_random_door_close
        - automation.notification_random_door_open
