###################################################
#
#  Home Assistant Main Configuration File
#
###################################################

#default_config:
api:
circadian_lighting:
config:
discovery:
logbook:
map:
mobile_app:
person:
shopping_list:
ssdp:
sun:
system_health:
updater:
zeroconf:

###################################################
#
# Automation components
#
###################################################

automation: !include_dir_merge_list package/automation
script: !include_dir_merge_named package/scripts

###################################################
#
# Components that needs a file with info
#
###################################################

alexa: !include compontents/devices/alexa.yaml
browser_mod: !include compontents/configs/browser_mod.yaml
customizer: !include compontents/configs/customizer.yaml
device_tracker: !include compontents/configs/device_tracker.yaml
frontend: !include compontents/configs/frontend.yaml
homeassistant: !include compontents/configs/homeassistant.yaml
homekit: !include compontents/configs/homekit.yaml
history: !include compontents/configs/history.yaml
http: !include compontents/configs/http.yaml
logger: !include compontents/configs/logger.yaml
nest: !include compontents/devices/nest.yaml
panel_custom: !include compontents/configs/panel_custom.yaml
recorder: !include compontents/configs/recorder.yaml
remote: !include compontents/devices/remote.yaml
rflink: !include compontents/devices/rflink.yaml
shell_command: !include compontents/devices/shell_commands.yaml
speedtestdotnet: !include compontents/configs/speedtest.yaml
tts: !include compontents/devices/tts.yaml
weather: !include compontents/configs/weather.yaml
zwave: !include compontents/devices/zwave.yaml

###################################################
#
# Components use merge to build configuration
#
###################################################

binary_sensor: !include_dir_list compontents/binary_sensors
calendar: !include_dir_list compontents/caldav
fan: !include_dir_list compontents/fan
group: !include_dir_merge_named compontents/groups
input_boolean: !include_dir_merge_named compontents/input_boolean
input_number: !include_dir_merge_named compontents/input_number
input_select: !include_dir_merge_named compontents/input_select
light: !include_dir_list compontents/light
media_player: !include_dir_list compontents/media_players
notify: !include_dir_list compontents/configs/notify
sensor: !include_dir_list compontents/sensors
switch: !include_dir_list compontents/switches
# timer: !include_dir_merge_named compontents/timer