# Configure a default setup of Home Assistant (frontend, api, etc)
#  
# https://github.com/poudenes/homeassistant

#default_config:

api:
config:
discovery:
shopping_list:
person:
map:
ssdp:
sun:
system_health:
updater:
logbook:
zeroconf:

customizer:
  custom_ui: local

zone: !include_dir_list package/compontents/zones
switch: !include_dir_list package/compontents/switches
sensor: !include_dir_list package/compontents/sensors
fan: !include_dir_list package/compontents/fan
media_player: !include_dir_list package/compontents/media_players
light: !include_dir_list package/compontents/light
binary_sensor: !include_dir_list package/compontents/binary_sensors
calendar: !include_dir_list package/compontents/caldav
group: !include_dir_merge_named package/compontents/groups
input_boolean: !include_dir_merge_named package/compontents/input_boolean
automation: !include_dir_merge_list package/automation
script: !include_dir_merge_named package/scripts
notify: !include_dir_list package/compontents/configs/notify

frontend: !include package/compontents/configs/frontend.yaml
homeassistant: !include package/compontents/configs/homeassistant.yaml
history: !include package/compontents/configs/history.yaml
apple_tv_mrp: !include package/compontents/devices/apple_tv_mrp.yaml
shell_command: !include package/compontents/devices/shell_commands.yaml
tts: !include package/compontents/devices/tts.yaml
rflink: !include package/compontents/devices/rflink.yaml
zwave: !include package/compontents/devices/zwave.yaml
remote: !include package/compontents/devices/remote.yaml
nest: !include package/compontents/devices/nest.yaml
logger: !include package/compontents/configs/logger.yaml
http: !include package/compontents/configs/http.yaml
speedtestdotnet: !include package/compontents/configs/speedtest.yaml 
weather: !include package/compontents/configs/weather.yaml
homekit: !include package/compontents/configs/homekit.yaml
recorder: !include package/compontents/configs/recorder.yaml

# android_ip_webcam: !include package/compontents/configs/camera.yaml
# panel_iframe: !include_dir_merge_named package/compontents/panel_iframe
# notify: !include package/compontents/configs/notify.yaml
# google: !include package/compontents/configs/google.yaml
# alexa: !include package/compontents/devices/alexa.yaml
# mobile_app:
