# Configure a default setup of Home Assistant (frontend, api, etc)
# Peter Oudenes
# 
# https://github.com/poudenes/homeassistant

frontend:
  themes: !include package/compontents/themes.yaml

default_config:
config:
api:
shopping_list:
discovery:

homeassistant:
  customize: !include_dir_merge_named package/customize/
  auth_providers:
    - type: homeassistant

shell_command:
  meek_fan_turn_off: 'curl http://192.168.100.113/control?cmd=event,FanOff'
  meek_fan_turn_on: 'curl http://192.168.100.113/control?cmd=event,FanOn'

tts:
  - platform: google_translate

panel_iframe:
  rijdendetreinen:
    title: 'NS'
    icon: mdi:train
    url: 'https://www.rijdendetreinen.nl/vertrektijden/station/amsterdam-zuid?style=tb&hide_train_numbers=1&hide_stock=1&time=both'
  ov9292:
    title: 'GVB'
    icon: mdi:bus
    url: 'https://9292.nl/amsterdam/tramhalte-metrostation-de-boelelaan-vu'

# CONFIGURATION COMPONENTS
rflink: !include package/compontents/rflink.yaml
zwave: !include package/compontents/zwave.yaml
logger: !include package/compontents/logger.yaml
http: !include package/compontents/http.yaml
google: !include package/compontents/google.yaml
nest: !include package/compontents/nest.yaml
notify: !include package/compontents/notify.yaml
speedtestdotnet: !include package/compontents/speedtest.yaml 
remote: !include package/compontents/remote.yaml
binary_sensor: !include package/compontents/binary_sensors.yaml
zone: !include package/compontents/zones.yaml
weather: !include package/compontents/weather.yaml
homekit: !include package/compontents/homekit.yaml
recorder: !include package/compontents/recorder.yaml
alexa: !include package/compontents/alexa.yaml
switch: !include package/compontents/switch.yaml
media_player: !include_dir_list package/media_players/
group: !include_dir_merge_named package/groups/
sensor: !include_dir_list package/sensors/
input_boolean: !include_dir_merge_named package/input_boolean/
light: !include_dir_merge_list package/light/

# AUTOMATION
automation: !include_dir_merge_list package/automation/
script: !include_dir_merge_named package/scripts/
