# Configure a default setup of Home Assistant (frontend, api, etc)
# Peter Oudenes
# 
# https://github.com/poudenes/homeassistant

frontend:
  themes: !include package/compontents/themes.yaml

default_config:
config:
api:
shopping_list:
discovery:

homeassistant:
  customize: !include_dir_merge_named package/customize/
  auth_providers:
    - type: homeassistant

shell_command:
  meek_fan_turn_off: 'curl http://192.168.100.113/control?cmd=event,FanOff'
  meek_fan_turn_on: 'curl http://192.168.100.113/control?cmd=event,FanOn'

life360:
  circles:
    include: [Family]
    
tts:
  - platform: google_translate

panel_iframe:
  rijdendetreinen:
    title: 'NS'
    icon: mdi:train
    url: 'https://www.rijdendetreinen.nl/vertrektijden/station/amsterdam-zuid?style=tb&hide_train_numbers=1&hide_stock=1&time=both'
  ov9292:
    title: 'GVB'
    icon: mdi:bus
    url: 'https://9292.nl/amsterdam/tramhalte-metrostation-de-boelelaan-vu'

# CONFIGURATION COMPONENTS ALL DEVICES SPLITUP IN OWN YAML
zone: !include_dir_list package/compontents/zones
switch: !include_dir_list package/compontents/switches
sensor: !include_dir_list package/compontents/sensors
media_player: !include_dir_list package/compontents/media_players
group: !include_dir_merge_named package/compontents/groups
input_boolean: !include_dir_merge_named package/compontents/input_boolean
light: !include_dir_list package/compontents/light/

# NEED TO BE DONE GET ERRORS
binary_sensor: !include package/compontents/binary_sensors/binary_sensors.yaml

# CONFIGURATION HARDWARE
rflink: !include package/compontents/devices/rflink.yaml
zwave: !include package/compontents/devices/zwave.yaml
remote: !include package/compontents/devices/remote.yaml
alexa: !include package/compontents/devices/alexa.yaml
nest: !include package/compontents/devices/nest.yaml

logger: !include package/compontents/logger.yaml
http: !include package/compontents/http.yaml
google: !include package/compontents/google.yaml
notify: !include package/compontents/notify.yaml
speedtestdotnet: !include package/compontents/speedtest.yaml 
weather: !include package/compontents/weather.yaml
homekit: !include package/compontents/homekit.yaml
recorder: !include package/compontents/recorder.yaml

automation: !include_dir_merge_list package/automation/
script: !include_dir_merge_named package/scripts/
