###################################################
#
#  Home Assistant Main Configuration File
#
#default_config:
#
###################################################

###################################################
#
# Components that not needed more info
#
###################################################

api:
circadian_lighting:
config:
discovery:
logbook:
map:
mobile_app:
person:
shopping_list:
ssdp:
sun:
system_health:
updater:
zeroconf:

###################################################
#
# Components that needs a file with info
#
device_tracker: !include package/compontents/configs/device_tracker.yaml
# android_ip_webcam: !include package/compontents/configs/camera.yaml
# panel_iframe: !include_dir_merge_named package/compontents/panel_iframe
# notify: !include package/compontents/configs/notify.yaml
# google: !include package/compontents/configs/google.yaml
#
###################################################

alexa: !include package/compontents/devices/alexa.yaml
browser_mod: !include package/compontents/configs/browser_mod.yaml
customizer: !include package/compontents/configs/customizer.yaml
frontend: !include package/compontents/configs/frontend.yaml
homeassistant: !include package/compontents/configs/homeassistant.yaml
homekit: !include package/compontents/configs/homekit.yaml
history: !include package/compontents/configs/history.yaml
http: !include package/compontents/configs/http.yaml
logger: !include package/compontents/configs/logger.yaml
nest: !include package/compontents/devices/nest.yaml
panel_custom: !include package/compontents/configs/panel_custom.yaml
recorder: !include package/compontents/configs/recorder.yaml
remote: !include package/compontents/devices/remote.yaml
rflink: !include package/compontents/devices/rflink.yaml
shell_command: !include package/compontents/devices/shell_commands.yaml
speedtestdotnet: !include package/compontents/configs/speedtest.yaml
tts: !include package/compontents/devices/tts.yaml
weather: !include package/compontents/configs/weather.yaml
zwave: !include package/compontents/devices/zwave.yaml

###################################################
#
# Components use merge to build configuration
#
###################################################

automation: !include_dir_merge_list package/automation
binary_sensor: !include_dir_list package/compontents/binary_sensors
calendar: !include_dir_list package/compontents/caldav
fan: !include_dir_list package/compontents/fan
group: !include_dir_merge_named package/compontents/groups
input_boolean: !include_dir_merge_named package/compontents/input_boolean
input_number: !include_dir_merge_named package/compontents/input_number
input_select: !include_dir_merge_named package/compontents/input_select
light: !include_dir_list package/compontents/light
media_player: !include_dir_list package/compontents/media_players
notify: !include_dir_list package/compontents/configs/notify
script: !include_dir_merge_named package/scripts
sensor: !include_dir_list package/compontents/sensors
switch: !include_dir_list package/compontents/switches
