# Configure a default setup of Home Assistant (frontend, api, etc)
# Peter Oudenes
# 
# https://github.com/poudenes/homeassistant

default_config:
config:
api:
shopping_list:
discovery:

frontend:
  themes: !include package/compontents/themes/themes.yaml

homeassistant:
  customize: !include_dir_merge_named package/customize/
  auth_providers:
    - type: homeassistant

shell_command:
  meek_fan_turn_off: 'curl http://192.168.100.113/control?cmd=event,FanOff'
  meek_fan_turn_on: 'curl http://192.168.100.113/control?cmd=event,FanOn'

life360:
  circles:
    include: [Family]
    
tts:
  - platform: google_translate

# CONFIGURATION COMPONENTS ALL DEVICES SPLITUP IN OWN YAML
zone: !include_dir_list package/compontents/zones
switch: !include_dir_list package/compontents/switches
sensor: !include_dir_list package/compontents/sensors
media_player: !include_dir_list package/compontents/media_players
group: !include_dir_merge_named package/compontents/groups
input_boolean: !include_dir_merge_named package/compontents/input_boolean
light: !include_dir_list package/compontents/light
binary_sensor: !include_dir_list package/compontents/binary_sensors
panel_iframe: !include_dir_merge_named package/compontents/panel_iframe

# CONFIGURATION HARDWARE
rflink: !include package/compontents/devices/rflink.yaml
zwave: !include package/compontents/devices/zwave.yaml
remote: !include package/compontents/devices/remote.yaml
alexa: !include package/compontents/devices/alexa.yaml
nest: !include package/compontents/devices/nest.yaml

logger: !include package/compontents/configs/logger.yaml
http: !include package/compontents/configs/http.yaml
google: !include package/compontents/configs/google.yaml
notify: !include package/compontents/configs/notify.yaml
speedtestdotnet: !include package/compontents/configs/speedtest.yaml 
weather: !include package/compontents/configs/weather.yaml
homekit: !include package/compontents/configs/homekit.yaml
recorder: !include package/compontents/configs/recorder.yaml

automation: !include_dir_merge_list package/automation/
script: !include_dir_merge_named package/scripts/
