alexa_speak_engine:
  alias: Alexa Speak Engine
  sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.peter_s_echo_dot
        volume_level: "{{ volume }}"

#    - delay: '00:00:02'

    - service: notify.alexa_media_peter_s_echo_dot
      data_template:
        target: media_player.this_device
        message: "{{ message }}"
        data:
          type: announce
