appletv_normal:
  alias: AppleTV Normal
  sequence:

    - service: light.turn_on
      data:
        entity_id: light.livingroom_wall
        kelvin: 2700
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id: light.livingroom_window
        kelvin: 2700
        brightness_pct: 70

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_all
        kelvin: 2700
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 50 }}"

    - service: light.turn_on
      data:
        entity_id: light.balcony
        brightness_pct: 100
        effect: 0

appletv_birthday:
  alias: AppleTV Birthday
  sequence:

    - service: light.turn_on
      data:
        entity_id: light.livingroom_all
        kelvin: 2700
        brightness_pct: 100

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_1
        effect: 0
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_2
        effect: 0
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_3
        effect: 0
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data:
        entity_id: light.balcony
        brightness_pct: 100
        effect: 0

appletv_halloween:
  alias: AppleTV Halloween
  sequence:

    - service: light.turn_on
      data:
        entity_id: light.livingroom_wall
        color_name: orange
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id: light.livingroom_window
        color_name: orange
        brightness_pct: 70

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_1
        color_name: blue
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_2
        color_color: purple
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_3
        color_name: blue
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data:
        entity_id: light.balcony
        brightness_pct: 100
        effect: 0

appletv_kingsday:
  alias: AppleTV Kingsday
  sequence:

    - service: light.turn_on
      data:
        entity_id: light.livingroom_all
        kelvin: 2700
        brightness_pct: 100

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_1
        color_name: red
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_2
        color_temp: 153
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_3
        color_name: blue
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"

    - service: light.turn_on
      data:
        entity_id: light.balcony
        brightness_pct: 100
        effect: 0

appletv_christmas:
  alias: AppleTV Christmas
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.livingroom_1
        color_name: red
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id: light.livingroom_2
        color_name: green
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id: light.livingroom_3
        color_name: green
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id: light.livingroom_4
        color_name: red
        brightness_pct: 100

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_1
        color_name: blue
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 75 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_2
        color_temp: 153
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 75 }}"

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_3
        color_name: blue
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 75 }}"

    - service: light.turn_on
      data:
        entity_id: light.balcony
        brightness_pct: 100
        effect: 0
