kodi_control_paused:
  alias: Kodi Control Paused Scene
  sequence:

    - service: light.turn_on
      data:
        entity_id: 
          - light.livingroom_wall
          - light.livingroom_window
        brightness_pct: 100
        transition: 5

    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
          - light.balcony
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id:
          - light.nanoleaf
        brightness_pct: 50
        transition: 5

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_all
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"
        transition: 5

# KODI IS PLAYING
kodi_control_playing:
  alias: Kodi Control Playing Scene
  sequence:

    - service: light.turn_on
      data:
        entity_id:
          - light.livingroom_wall
        brightness_pct: 70
        transition: 5

    - service: light.turn_on
      data:
        entity_id:
          - light.livingroom_window
        brightness_pct: 20 
        transition: 5

    - service: light.turn_on
      data:
        entity_id:
          - light.nanoleaf
        brightness_pct: 30
        transition: 5

    - service: light.turn_on
      data:
        entity_id:
          - light.balcony
        brightness_pct: 25

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_all
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 25 }}"
        transition: 5

    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all

# KODI IS IDLE
kodi_control_idle:
  alias: Kodi Control Idle Scene
  sequence:

    - service: light.turn_on
      data:
        entity_id:
          - light.livingroom_wall
          - light.livingroom_window
          - light.balcony
        brightness_pct: 100
        transition: 5
 
    - service: light.turn_on
      data:
        entity_id:
          - light.nanoleaf
        brightness_pct: 50
        transition: 5

    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_all
        brightness_pct: "{{ 0 if is_state('binary_sensor.node_10', 'on') else 100 }}"
        transition: 5

    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
