###########################################################################################
# NEST ENABLE/DISABLE CONTROL NEST TEMP BASED ON TEMP INSIDE AND OUTSIDE
###########################################################################################

- alias: "Control - Disable Nest Control"
  trigger:

    platform: state
    entity_id: switch.mqtt_disable_nest_control

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ 'Automation Nest Control is disabled' if is_state('switch.mqtt_disable_nest_control', 'on') else 'Automation Nest Control is enable' }}"
        priority: 0
        sound: bike
        title: "HA Scene System"

    - service_template: "{{ 'automation.turn_off' if is_state('switch.mqtt_disable_nest_control', 'on') else 'automation.turn_on' }}"
      entity_id:
        - automation.control_nest_control_goodnight_scene
        - automation.control_nest_control_nobody_home
        - automation.control_nest_control_someone_home
