###########################################################################################
# NEST CONTROL TEMP BASED ON SCENE GOODNIGHT
###########################################################################################

- alias: "Control - Nest Control Goodnight Scene"
  trigger:

  - platform: state
    entity_id: switch.mqtt_scene_goodnight
    to: "on"

  - platform: state
    entity_id: climate.entryway

  condition:
    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "on"

  action:
    service: climate.set_temperature
    data:
      entity_id: climate.entryway
      temperature: 9
