###########################################################################################
# NEST CONTROL TEMP BASED ON SOMEONE HOME AND TEMP INSIDE AND OUTSIDE
###########################################################################################

- alias: "Control - Nest Control Someone Home"
  trigger:

    - platform: state
      entity_id: binary_sensor.sensor_manual_family_home
      to: "on"

    - platform: state
      entity_id: switch.mqtt_scene_goodnight
      to: "off"

    - platform: state
      entity_id: climate.entryway

  condition:
    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

  action:
    service: climate.set_temperature
    data_template:
      entity_id: climate.entryway
      temperature: >-
        {% set outside = states('sensor.buienradar_temperature') | float %}
        {% set inside = states('sensor.climate_temp_inside') | float %}
        {% if outside > 12 and inside > 15 %} 10
        {% elif outside < 12 and inside > 15 %} 10
        {% elif outside < 12 and inside < 15 %} 21
        {% else %} 9
        {% endif %}
