- alias: 'Control - Nest Control Nobody Home'
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
    - condition: state
      entity_id: group.group_family
      state: not_home 
  action:
    - service: climate.set_temperature
      entity_id: climate.entryway
      data_template:
        temperature: >
          {% set tempnest3 = states('sensor.entryway_thermostat_target') | float %}
          {% if tempnest3 > 11 %} 9
          {% else %} 9
          {% endif %}
