###########################################################################################
#
# PATCH WHEN GROUP 0 IS ON OR OFF THE CORRECT STATUS WILL SEND TO MILIGHT HUB FOR ALL LIGHTS INSIDE GROUP
#
###########################################################################################

- alias: "Patches - MiLight Kitchen Group 0"
  initial_state: "true"
  trigger:

    platform: mqtt
    topic: "milight/states/0xAAA2/rgb_cct/0"

  action:
    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAA2/rgb_cct/1"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAA2/rgb_cct/2"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAA2/rgb_cct/3"
        payload_template: "{{ trigger.payload }}"
