- alias: 'Scene - Nobody Home'
  trigger:

  - platform: time_pattern
    minutes: /1

  - entity_id: device_tracker.geofency_peter
    platform: state
    to: 'not_home'

  - entity_id: device_tracker.geofency_kay
    platform: state
    to: 'not_home'

  condition:
    - condition: state
      entity_id: group.group_family
      state: not_home 

    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'off'

  action:
  - service: notify.pushover
    data:
      message: "Scene Nobody Home is activated"
      title: "HA Scene System"

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.scene_daylight

  - service: input_boolean.turn_off
    entity_id: 
      - input_boolean.scene_kodi
      - input_boolean.scene_tv
      - input_boolean.scene_iptv
      - input_boolean.scene_evening
      - input_boolean.scene_appletv
      - input_boolean.scene_sexy

# TURN OFF ALL LIGHT
  - service: script.nobody_home
