- alias: Scene - Goodnight
  trigger:

  - entity_id: input_boolean.scene_goodnight
    platform: state
    to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'on'

  action:
  - service: notify.pushover
    data:
      message: Scene goodnight is activated

  - service: input_boolean.turn_off
    data:
      entity_id: 
        - input_boolean.scene_kodi
        - input_boolean.scene_tv
        - input_boolean.scene_iptv
        - input_boolean.scene_daylight
        - input_boolean.scene_appletv
        - input_boolean.scene_sexy
        - input_boolean.scene_evening

# LOGITECH TURN OFF
  - service: remote.turn_off
    entity_id: remote.logitech_harmony

# NANOLEAF LIGHT
  - service: light.turn_off
    entity_id: light.nanoleaf

# LIGHT SCENES
  - service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      kelvin: 4000
      brightness_pct: "{{ 50 if is_state('binary_sensor.node_12', 'on') else 100 }}"

  - service: homeassistant.turn_on
    data_template:
      entity_id: light.newkaku_01401eb6_a
      brightness_pct: >
        {% if (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'on' %} 100
        {% else %} 0
        {% endif %}

  - service: light.turn_on
    entity_id: light.bathroom_all
    data:
      kelvin: 4000
      brightness_pct: 100

  - service: shell_command.meek_fan_turn_off

  - service: light.turn_on
    data:
      entity_id:
        - light.hallway
        - light.kitchen_all
        - light.sink_all
        - light.toilet_all
        - light.dressoir_all
        - light.livingroom_all
      kelvin: 2700
      brightness_pct: 20

  - delay: 00:00:05

  - service: light.turn_off
    data:
      entity_id:
        - light.hallway
        - light.kitchen_all
        - light.sink_all
        - light.toilet_all
        - light.dressoir_all
        - light.livingroom_all
        - light.balcony 

  - service: script.turn_on
    entity_id: script.alexa_speak_engine
    data_template:
      variables:
#        volume: '0.5'
        message: >
          {{ [
          "Sleep Tight, Don't let the bedbugs bite.",
          "Have pleasant dreams",
          "As they say in the Navy, See you in the rise."
          "Dream pleasant dreams.  Tomorrow is a new day.",
          "Early sleep and early wake up gives health and makes you grow.",
          "Good night, good night! Parting is such sweet sorrow that I shall say goodnight till it is Morrow.",
          "There is a time for many words, and there is also a time for sleep.",
          "This good night isn’t meant to bring an end to this day. It’s intended to wish you awesomeness in what lies ahead.",
          "Stuff your worries in your pillow, wrap your troubles in your blanket and spread your anxieties on your sheets. When you wake up tomorrow, you may have dirty linen, but more importantly, you’ll have a fresh mind and a happy heart. Good night.",
          "Goodnight, talk to you tomorrow. ",
          "Goodnight sweetheart. ",
          "Go to bed, you sleepy head! ",
          "Nighty Night. ",
          "Sleep snug as a bug in a rug! ",
          "Lights out! ... Uh huh. ... Dance, dance dance. ",
          "Time to ride the rainbow to dreamland! ",
          "Sweet dreams. ",
          "See ya' in the mornin'! ",
          "I-ill be right here when you wake up. moo ahh .. ha .. ha ",
          "I-ill be dreaming of your face! ",
          "You're the most wonderful user in the whole world! ",
          "I'm yours, forever and always. ",
          "Parting is such sweet sorrow, that I shall say good night till it be tomorrow. ",
          "Can you hear that? ... Its your soft warm bed calling your name. You really must go and see what it wants. ",
          "Grumpy cat says goodnight.",
          "Goodnight, sweet dreams. ",
          "You have so much to be greatful for... goodnight.",
          "Wishing you a goodnight and sweatest dreams.",
          "What about good night kisses? "
          ] | random }}
