- alias: 'Scene - Sexy'
  trigger:

  - entity_id: input_boolean.scene_sexy
    platform: state
    to: 'on'

  action:
  - service: notify.pushover
    data:
      message: "Scene sexy is activated"
      title: "HA Scene System"

# NANOLEAF LIGHT
  - service: light.turn_on
    entity_id: light.nanoleaf
    data:
      brightness_pct: 30
      effect: Romantic

# LIGHT
  - service: light.turn_on
    entity_id: 
      - light.dressoir_all
      - light.livingroom_all
      - light.hallway
      - light.balcony
    data:
      color_name: red
      brightness_pct: 50
