- alias: 'Scene - Kodi'
  trigger:

  - platform: time_pattern
    minutes: /1

  - entity_id: device_tracker.geofency_peter
    platform: state
    to: home

  - entity_id: device_tracker.geofency_kay
    platform: state
    to: home

  - entity_id: sensor.harmony
    platform: state
    to: 'Kodi'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - condition: state
      entity_id: input_boolean.scene_kodi
      state: 'off'

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off'

    - condition: state
      entity_id: sensor.harmony
      state: 'Kodi'

    - condition: state
      entity_id: group.group_family
      state: home 

  action:
  - service: notify.pushover
    data:
      message: Scene kodi is activated

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.scene_kodi

  - service: input_boolean.turn_off
    entity_id: 
      - input_boolean.scene_evening
      - input_boolean.scene_tv
      - input_boolean.scene_iptv
      - input_boolean.scene_daylight
      - input_boolean.scene_appletv
      - input_boolean.scene_sexy

# TTS TO ALEXA
  - service: script.engine_say
    data_template:
      media_player: media_player.this_device
      say_scene_kodi: "true"

# NANOLEAF LIGHT
  - service: light.turn_on
    entity_id: light.nanoleaf
    data_template:
      brightness_pct: 30
      effect: >
        {% if (states.sensor.holiday.state) == 'Christmas' %} Christmas
        {% elif (states.sensor.holiday.state) == 'Halloween' %} Halloween
        {% elif (states.sensor.holiday.state) == 'Kingsday' %} Kingsday
        {% elif (states.sensor.holiday.state) == 'Birthday' %} Kingsday
        {% else %} Fireplace
        {% endif %}

# LIGHT
  - service_template: >
       {% if (states.sensor.holiday.state) == 'Christmas' %} script.evening_christmas
       {% elif (states.sensor.holiday.state) == 'Halloween' %} script.evening_halloween
       {% elif (states.sensor.holiday.state) == 'Kingsday' %} script.evening_kingsday
       {% elif (states.sensor.holiday.state) == 'Birthday' %} script.evening_birthday
       {% else %} script.evening_normal
       {% endif %}

# DINING TABLE
  - service: homeassistant.turn_on
    data_template:
      entity_id: light.newkaku_01401eb6_a
      brightness_pct: >
        {% if (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'on' %} 100
        {% elif (states.binary_sensor.node_10.state) == 'off' and (states.switch.kay_learning.state) == 'on' %} 100 
        {% else %} 0
        {% endif %}

# CORRECT THE LIGHT SCENE ON STATUS KODI
  - service_template: >
      {% if (states.media_player.kodi.state) == 'playing' %} script.kodi_control_playing
      {% elif (states.media_player.kodi.state) == 'paused' %} script.kodi_control_paused
      {% else %} script.kodi_control_idle
      {% endif %}
