###########################################################################################
# MQTT SWITCH
# https://www.home-assistant.io/integrations/switch.mqtt/
###########################################################################################
---
platform: mqtt
command_topic: "homeassistant/switch/disable_nest_control"
state_topic: "homeassistant/switch/disable_nest_control"
payload_on: "1"
payload_off: "0"
state_on: "1"
state_off: "0"
name: "MQTT Disable Nest Control"
optimistic: false
qos: 0
retain: true
