- alias: Control - Turn on Zwave 4 and 5
  trigger:
    - entity_id: device_tracker.geofency_peter
      platform: state
      to: home
    - entity_id: device_tracker.geofency_kay
      platform: state 
      to: home

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.geofency_kay
          state: home
        - condition: state
          entity_id: device_tracker.geofency_peter
          state: home

  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.node_5_switch
          - switch.node_6_switch
          - switch.node_7_switch

- alias: Control - Turn off Zwave 4 and 5
  trigger:
    - entity_id: device_tracker.geofency_kay
      platform: state
      to: not_home

    - entity_id: device_tracker.geofency_peter
      platform: state
      to: not_home

  condition:
    - condition: state
      entity_id: device_tracker.geofency_kay
      state: not_home
    - condition: state
      entity_id: device_tracker.geofency_peter
      state: not_home

  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.node_5_switch
          - switch.node_6_switch
          - switch.node_7_switch
