---
switch.toilet:
  friendly_name: Toilet Switch
  homebridge_name: Toilet Switch
switch.newkaku_0114ef92_b:
  friendly_name: Wall Switch
  homebridge_name: Wall Switch
switch.newkaku_0114ef92_c:
  friendly_name: Window Switch
  homebridge_name: Window Switch
switch.newkaku_011fdd46_b:
  friendly_name: Balcony Switch
  homebridge_name: Balcony Switch
switch.newkaku_011fdd46_c:
  friendly_name: Dressoir Switch
  homebridge_name: Dressoir Switch
light.newkaku_01401eb6_a:
  friendly_name: Diningroom Switch
  homebridge_name: Diningroom Switch
switch.newkaku_01074522_a:
  friendly_name: Bedroom Switch
  homebridge_name: Bedroom Switch
switch.newkaku_011fad02_b:
  friendly_name: Sink Switch
  homebridge_name: Sink Switch
switch.newkaku_011fad02_c:
  friendly_name: Cooker Switch
  homebridge_name: Cooker Switch
switch.newkaku_014ad3ba_a:
  friendly_name: Kitchen Switch
  homebridge_name: Kitchen Switch
switch.newkaku_01616a32_a:
  friendly_name: Bathroom Switch
  homebridge_name: Bathroom Switch
switch.newkaku_014e5906_a:
  friendly_name: Test Button
  homebridge_name: Test Button
switch.newkaku_016138ba_a:
  friendly_name: Hallway Switch
  homebridge_name: Hallway Switch
