- alias: Switch - Sink On
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fad02_b
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.sink_all
    data:
      brightness_pct: 100
      kelvin: 2700

- alias: Switch - Sink Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fad02_b
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.sink_all
