- alias: Switch - Balcony On
  trigger:
    - platform: state
      entity_id: switch.newkaku_016138ba_a
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.hallway
    data:
      brightness_pct: 100
      kelvin: 2700

- alias: Switch - Balcony Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_016138ba_a
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.hallway
