- alias: Switch - Wall On
  trigger:
    - platform: state
      entity_id: switch.newkaku_0114ef92_b
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.livingroom_wall
    data:
      brightness_pct: 100
      kelvin: 2700

- alias: Switch - Wall Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_0114ef92_b
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.livingroom_wall
