zwave.node_11:
  friendly_name: Fibaro Door
sensor.node_11_access_control:
  friendly_name: Fibaro Door Access Control
sensor.node_11_alarm_level:
  friendly_name: Fibaro Door Alarm Level
sensor.node_11_alarm_type:
  friendly_name: Fibaro Door Alarm Type
sensor.node_11_burglar:
  friendly_name: Fibaro Door Burglar
sensor.node_11_luminance:
  friendly_name: Fibaro Door Lux
sensor.node_11_sourcenodeid:
  friendly_name: Fibaro Door SourceID
sensor.node_11_temperature:
  friendly_name: Fibaro Door Temp
sensor.node_11_power_management:
  friendly_name: Fibaro Door Power Man
sensor.node_11_heat:
  friendly_name: Fibaro Door Heat
binary_sensor.node_11:
  friendly_name: Fibaro Door
