zwave.node_12:
  friendly_name: Neo Door
sensor.node_12_access_control:
  friendly_name: Neo Door Access Control
sensor.node_12_alarm_level:
  friendly_name: Neo Door Alarm Level
sensor.node_12_alarm_type:
  friendly_name: Neo Door Alarm Type
sensor.node_12_burglar:
  friendly_name: Neo Door Burglar
sensor.node_12_luminance:
  friendly_name: Neo Door Lux
sensor.node_12_sourcenodeid:
  friendly_name: Neo Door SourceID
sensor.node_12_temperature:
  friendly_name: Neo Door Temp
sensor.node_12_power_management:
  friendly_name: Neo Door Power Man
sensor.node_12_heat:
  friendly_name: Neo Door Heat
binary_sensor.node_12:
  friendly_name: Neo Door
