platform: command_line
command: 'cat /config/config/calendar.json'
name: Birthday 
scan_interval: 5
value_template: >
  {% set today = now().month  ~ '/' ~ now().day  %}
  {% set birthday =  value_json.HA_CALENDAR.birthday[ today ] %}
    {% if birthday | trim == "" %}
         {% set birthday =  "No Birthday today" %}
       {% endif %}
  {{ birthday }}
