platform: darksky
api_key: !secret darsky_apikey
latitude: 52.370216
longitude: 4.895168
forecast: 2
language: nl
scan_interval: 
  minutes: 30
monitored_conditions:
  - summary
  - wind_speed
  - wind_bearing
  - visibility
  - temperature_high
  - temperature_low
  - temperature
  - dew_point
  - humidity
  - pressure
  - hourly_summary
  - daily_summary
  - uv_index
  - moon_phase
  - cloud_cover
