platform: command_line
command: 'cat /config/config/calendar.json'
name: Holiday Json
scan_interval: 5
value_template: >
  {% set today = now().month  ~ '/' ~ now().day  %}
  {% set holiday =  value_json.HA_CALENDAR.holiday[ today ] %}
    {% if holiday | trim == "" %}
         {% set holiday =  "No holiday today" %}
       {% endif %}
  {{ holiday }}
