- alias: 'Patches - Fibaro Frontdoor Sensor Open'
  trigger:
  - entity_id: sensor.node_11_access_control
    platform: state
    to: '22'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.fibaro_frontdoor

- alias: 'Patches - Fibaro Frontdoor Sensor Close'
  trigger:
  - entity_id: sensor.node_11_access_control
    platform: state
    to: '23'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.fibaro_frontdoor

- alias: 'Patches - Fibaro iMac Sensor Open'
  trigger:
  - entity_id: sensor.node_13_access_control
    platform: state
    to: '22'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.fibaro_imac

- alias: 'Patches - Fibaro iMac Sensor Close'
  trigger:
  - entity_id: sensor.node_13_access_control
    platform: state
    to: '23'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.fibaro_imac
