- alias: Patch - Fibaro Frontdoor Sensor Open
  trigger:
  - entity_id: sensor.node_11_access_control
    platform: state
    to: '22'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.fibaro_frontdoor

- alias: Patch - Fibaro Frontdoor Sensor Close
  trigger:
  - entity_id: sensor.node_11_access_control
    platform: state
    to: '23'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.fibaro_frontdoor

- alias: Patch - Fibaro iMac Sensor Open
  trigger:
  - entity_id: sensor.node_13_access_control
    platform: state
    to: '22'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.fibaro_imac

- alias: Patch - Fibaro iMac Sensor Close
  trigger:
  - entity_id: sensor.node_13_access_control
    platform: state
    to: '23'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.fibaro_imac
