- alias: Control - AppleTV is playing
  trigger:
  - entity_id: media_player.woonkamer
    platform: state
    to: playing
    for:
      seconds: 10

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'  

  action:
    - service: script.appletv_control_playing

- alias: Control - AppleTV is on pause
  trigger:
  - entity_id: media_player.woonkamer
    from: playing
    platform: state
    to: paused

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon' 
 
  action:
    - service: script.appletv_control_paused

- alias: Control - AppleTV is idle
  trigger:
  - entity_id: media_player.woonkamer
    from: playing
    platform: state
    to: idle

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon' 

  action:
    - service: script.appletv_control_idle
