- alias: 'Notification - Kay Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_kay
    event: enter
    platform: zone
    zone: zone.home

  action:
  - data:
      message: Kay arrived home
    service: notify.pushover

- alias: 'Notification - Kay Left Home'
  trigger:
  - entity_id: device_tracker.geofency_kay
    event: leave
    platform: zone
    zone: zone.home

  action:
  - data:
      message: Kay left home
    service: notify.pushover
