- alias: 'Notification - Kay Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_kay
    event: enter
    platform: zone
    zone: zone.home

  action:
  - service: notify.pushover
    data:
      message: "Kay arrived home"
      title: "HA System"

- alias: 'Notification - Kay Left Home'
  trigger:
  - entity_id: device_tracker.geofency_kay
    event: leave
    platform: zone
    zone: zone.home

  action:
  - service: notify.pushover
    data:
      message: "Kay left home"
      title: "HA System"
