- alias: Control - Kodi is playing
  trigger:
  - entity_id: media_player.kodi
    platform: state
    to: playing

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'  

  action:
    - service: script.kodi_control_playing

- alias: Control - Kodi is on pause
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: paused

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon' 
 
  action:
    - service: script.kodi_control_paused

- alias: Control - Kodi is idle
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon' 

  action:
    - service: script.kodi_control_idle
