- alias: 'LetsEncrypt renewal'
  trigger:
  - platform: time
    at: '02:00:00'

  action:
  - service: hassio.addon_stop
    data:
      addon: core_nginx_proxy

  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt

  - delay: '00:01:30'

  - service: hassio.addon_start
    data:
      addon: core_nginx_proxy
