- alias: 'Notification - Login Failure'
  hide_entity: False
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.http_login') != 'unknown' }}"

  action:
  - service: notify.pushover
    data_template:
      message: There is a bad login registered on Home Assistant
