- alias: "Notification - Update Available Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.updater

  condition:
    - condition: template
      value_template: "{{ states('binary_sensor.updater') != 'unknown' }}"

  action:
  - service: notify.pushover
    data_template:
      message: "Home Assistant update is now available. {{now().strftime('%Y-%m-%d %I:%M %p')}}"
