- alias: "Notification - Update Available Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater

  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:
  - service: notify.pushover
    data_template:
      message: "Home Assistant {{ states.updater.updater.state }} is now available. {{now().strftime('%Y-%m-%d %I:%M %p')}}"
