- alias: 'Notification - Peter Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    event: enter
    platform: zone
    zone: zone.home

  action:
  - service: notify.pushover
    data:
      message: "Peter arrived home"
      title: "HA System"

- alias: 'Notification - Peter Left Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    event: leave
    platform: zone
    zone: zone.home

  action:
  - service: notify.pushover
    data:
      message: "Peter left home"
      title: "HA System"
