- alias: 'Notification - Peter Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    event: enter
    platform: zone
    zone: zone.home

  action:
  - data:
      message: Peter arrived home
    service: notify.pushover

- alias: 'Notification - Peter Left Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    event: leave
    platform: zone
    zone: zone.home

  action:
  - data:
      message: Peter left home
    service: notify.pushover
