- alias: Notification - Peter Arrive Home
  trigger:
  - entity_id: device_tracker.geofency_peter
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: Peter arrived home
    service: notify.pushover

#  - delay: 00:00:10
#
#  - service: tts.google_translate_say
#    data:
#      entity_id: media_player.modipu
#      message: The scene goodnight is activated! 


- alias: Notification - Peter Left Home
  trigger:
  - entity_id: device_tracker.geofency_peter
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: Peter left home
    service: notify.pushover
