- alias: 'Patches - MiLight Sink Group 0'
  initial_state: True
  trigger:
    platform: mqtt
    topic: milight/states/0xAAA1/rgb_cct/0
  action:
    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAA1/rgb_cct/1"
        payload_template: >-
          {{ trigger.payload }}

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAA1/rgb_cct/2"
        payload_template: >-
          {{ trigger.payload }}

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAA1/rgb_cct/3"
        payload_template: >-
          {{ trigger.payload }}
