---
zwave.node_18:
  friendly_name: Neo Motion Diningroom
sensor.node_18_alarm_level:
  friendly_name: Neo Motion Diningroom Alarm Level
sensor.node_18_alarm_type:
  friendly_name: Neo Motion Diningroom Alarm Type
sensor.node_18_burglar:
  friendly_name: Neo Motion Diningroom Burglar
sensor.node_18_luminance:
  friendly_name: Neo Motion Diningroom Lux
sensor.node_18_sourcenodeid:
  friendly_name: Neo Motion Diningroom SourceID
sensor.node_18_temperature:
  friendly_name: Neo Motion Diningroom Temp
binary_sensor.node_18:
  friendly_name: Neo Motion Diningroom
