---
zwave.node_14:
  friendly_name: Neo Motion Bedroom
sensor.node_14_alarm_level:
  friendly_name: Neo Motion Bedroom Alarm Level
sensor.node_14_alarm_type:
  friendly_name: Neo Motion Bedroom Alarm Type
sensor.node_14_burglar:
  friendly_name: Neo Motion Bedroom Burglar
sensor.node_14_luminance:
  friendly_name: Neo Motion Bedroom Lux
sensor.node_14_sourcenodeid:
  friendly_name: Neo Motion Bedroom SourceID
sensor.node_14_temperature:
  friendly_name: Neo Motion Bedroom Temp
binary_sensor.node_14:
  friendly_name: Neo Motion Bedroom
