###########################################################################################
#
# FAN STILL ON BATHROOM AND KITCHEN SENSORS ARE OFF
#
###########################################################################################

- alias: "Control - Fan still on"
  trigger:

    platform: state
    entity_id: binary_sensor.node_15 # Motion Bathroom

    platform: state
    entity_id: binary_sensor.node_16 # Motion Kitchen

  action:
    - service_template: >-
        {% if states('binary_sensor.node_16') == 'off' and states('binary_sensor.node_15') == 'off' %} fan.turn_off
        {% else %} script.none
        {% endif %}
      entity_id: fan.afzuiging_badkamer

    - service: script.pushover_engine
      data_template:
        message: "Bathroom and Kitchen off, turn off Fan"
        priority: 0
        sound: bike
        title: "HA System"
