- alias: "System - Start Automation after start HomeKit"
  hide_entity: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: "00:01:00"

    - service: homekit.start

    - service: automation.turn_on
      entity_id:
        - automation.notification_random_door_close
        - automation.notification_random_door_open
