- alias: 'System - Peter Left or Arrive Home Manual'
  trigger:
  - entity_id: device_tracker.geofency_peter
    platform: state

  action:
    - service_template: >-
        {% if (states.device_tracker.geofency_peter.state) == 'home' %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      data:
        entity_id: input_boolean.peter_home_manual
