###########################################################################################
#
# SYSTEM FKB TURN OFF AND ON SCREEN BASED ON 2 SENSORS
#
###########################################################################################

- alias: "System - FKB Screen On Off"
  trigger:
    - platform: state
      entity_id: binary_sensor.node_17

    - platform: state
      entity_id: binary_sensor.node_16

  action:
    service_template: >-
      {% if (states.binary_sensor.node_17.state) == 'on' or (states.binary_sensor.node_16.state) == 'on' %} shell_command.fullykiosk_screen_on
      {% else %} shell_command.fullykiosk_sceen_off
      {% endif %}
