###########################################################################################
#
# CLEAR LOGfILE IF SIZE IS > 50 MB
#
###########################################################################################

- alias: "System - Clear HA Log file"
  initial_state: true
  trigger:

    platform: numeric_state
    entity_id: sensor.home_assistant_log
    above: 50

  action:
    service: shell_command.clear_logs
