- alias: "System - Kay Left or Arrive Locative or GeoFency Manual"
  trigger:
    platform: state
    entity_id:
      - device_tracker.e7b5aad4_fc4c_4ee8_98fd_2337da788a0f
      - device_tracker.geofency_kay
  action:
    - service_template: >-
        {% if trigger.to_state.state == 'home' %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.kay_home_manual 
