###########################################################################################
# SYSTEM WHEN AUTOMATION TRACKER NOT WORK WE CAN MANUAL TURN ON OFF OF PETER IS AT HOME OR NOT
###########################################################################################

- alias: "System - Peter Left or Arrive Locative or GeoFency Manual"
  trigger:

    platform: state
    entity_id:
      - device_tracker.1717fe36_3c70_4599_963c_b70b6ee95eba
      - device_tracker.peter_iphone_geofency
      - device_tracker.peter_iphone_ha

  action:
    - service_template: >-
        {% if trigger.to_state.state == 'home' %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.peter_home_manual

    - service: script.pushover_engine
      data_template:
        message: >-
          {% if trigger.to_state.state == 'home' %}
            Peter arrived home
          {% else %}
            Peter left home
          {% endif %}
        priority: "0"
        sound: "bike"
        title: "HA Notify Engine"
