###########################################################################################
#
# SYSTEM Z-WAVE HEAL EVERY NIGHT AT 2:31 AM
#
###########################################################################################

- alias: "System - Z-Wave Nightly Heal"
  trigger:

    platform: time
    at: "2:31:00"

  action:
    service: zwave.heal_network
