- alias: "System - Start random door open close automation"
  trigger:  
      platform: homeassistant
      event: start
      
  action:
    - delay: "00:01:00"

    - service: automation.turn_on
      entity_id:
        - automation.notification_random_door_open_close
