###########################################################################################
#
# SYSTEM UPDATE KW SENSOR EVERY MINUTE
#
###########################################################################################

- alias: "System - Update Kw Sensor Template"
  trigger:
    platform: time_pattern
    minutes: "/1"
  action:
    service: homeassistant.update_entity
    entity_id: sensor.kw_1min
