###########################################################################################
# SYSTEM ENABLE RANDOM DOORS OPEN AUTOMATION AFTER HA START OTHERWISE VALUES ARE INCORRECT
###########################################################################################

- alias: "System - Restart SSL Cert after HA is started"
  trigger:
      platform: homeassistant
      event: start

  action:
    - delay: "00:01:00"

    - service: homeassistant.update_entity
      data:
        entity_id: sensor.ssl_certificate_expiry
