- alias: "System - AutoBackup on Monday and Saterday at 4AM"
  initial_state: true
  trigger:
    platform: time
    at: "04:00:00"

  condition:
    condition: time
    weekday:
      - mon
      - tue
      - sat

  action:
    - service: auto_backup.snapshot_full
      data_template:
        name: "AutoBackup - Full Backup: {{ now().strftime('%Y-%m-%d') }}" 
        keep_days: 7

    - service: script.pushover_engine
      data_template:
        message: "AutoBackup Full Backup is Running. The snapshot name is ->  Full Backup: {{ now().strftime('%Y-%m-%d') }}"
        priority: 0
        sound: bike
        title: "HA AutoBackup"