###########################################################################################
#
# FLUX
#
# https://www.home-assistant.io/integrations/flux/
#
###########################################################################################
---
platform: flux
lights:
  - light.bedroom_all
name: "Flux Bedroom"
start_time: "13:30:00"
stop_time: "14:00"
start_colortemp: 6500
#sunset_colortemp: 3000
stop_colortemp: 2700
brightness: 255
disable_brightness_adjust: "true"
mode: xy
transition: 30
interval: 30