###########################################################################################
#
# CONTROL LIGHT KITCHEN WHEN DAYTIME SCENE IS OFF
#
###########################################################################################

- alias: "Motion Detection - Bathroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_17 # Motion Bathroom

  action:
    - service_template: "{{ 'switch.turn_on' if is_state('binary_sensor.node_17', 'on') else 'switch.turn_off' }}"
      entity_id: switch.meek_bathroom

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/bathroom'
        payload: "{{ 1 if is_state('binary_sensor.node_17', 'on') else 0 }}"
