###########################################################################################
# CONTROL BEDROOM LIGHTS WHEN DOOR SENSOR IS ON OR OFF
###########################################################################################

- alias: "Door Sensor - Bedroom Door Open Close"
  trigger:

    platform: state
    entity_id: binary_sensor.neo_bedroomdoor_custom_sensor

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: light.bedroom_all
      state: "on"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      brightness_pct: >-
        {% if states('binary_sensor.neo_bedroomdoor_custom_sensor') == 'on' and (states('sensor.season') == 'autumn' or states('sensor.season') == 'winter') %} 100
        {% elif states('binary_sensor.neo_bedroomdoor_custom_sensor') == 'on' and (states('sensor.season') == 'spring' or states('sensor.season') == 'summer') %} 20
        {% else %} 100
        {% endif %}
