###########################################################################################
#
# CONTROL LIGHT DRESSOIR WHEN GOODNIGHT SCENE IS ACTIVE
#
###########################################################################################

- alias: "Motion Detection - Diningroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_18 # Motion Diningroom

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "on"

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

  action:
    - service_template: "{{ 'switch.turn_on' if is_state('binary_sensor.node_18', 'on') else 'switch.turn_off' }}"
      entity_id: switch.meek_dressoir

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/diningroom'
        payload: "{{ 1 if is_state('binary_sensor.node_18', 'on') else 0 }}"
