###########################################################################################
#
# KITCHEN CONTROL LIGHTS BASED ON SENSOR STATUS AND EVENT
#
###########################################################################################

- alias: "Motion Detection - Kitchen On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_16 # Motion Kitchen

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_daytime
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_cooking
      state: "off"

  action:
    - service_template: >-
        {% if (states.sensor.holiday.state) == 'Christmas' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_christmas_turn_on
        {% elif (states.sensor.holiday.state) == 'Halloween' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_halloween_turn_on
        {% elif (states.sensor.holiday.state) == 'Kingsday' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_kingsday_turn_on
        {% elif (states.sensor.holiday.state) == 'Birthday' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_birthday_turn_on
        {% else %} script.kitchen_normal_turn_on
        {% endif %}

    - service_template: >-
        {% if (states.binary_sensor.node_16.state) == 'on' %} switch.turn_on
        {% else %} switch.turn_off
        {% endif %}
      entity_id:
        - switch.meek_kitchen_seeling
        - switch.meek_kitchen_sink
        - switch.meek_cooking

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/kitchen'
        payload: "{{ 1 if is_state('binary_sensor.node_16', 'on') else 0 }}"
