###########################################################################################
#
# DININGROOM LIGHTS CONTROL WHEN DININGROOM SENSOR IS ON OR OFF
#
###########################################################################################

- alias: "Motion Detection - Diningroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_18 # Motion Diningroom

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

  action:
    - service: light.turn_on
      data_template:
        entity_id: light.dressoir_all
        brightness_pct: "{{ 20 if is_state('binary_sensor.node_18', 'on') else 0 }}"

    - service_template: >-
        {% if (states.binary_sensor.node_18.state) == 'on' %} switch.turn_on
        {% elif (states.binary_sensor.node_18.state) == 'off' %} switch.turn_off
        {% endif %}
      entity_id: switch.meek_dressoir

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/diningroom'
        payload: "{{ 1 if is_state('binary_sensor.node_18', 'on') else 0 }}"
