###########################################################################################
#
# HALLWAY CONTROL LIGHTS BASED ON SENSOR AND SCENE GOODNIGHT
#
###########################################################################################

- alias: "Motion Detection - Hallway On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_17 # Motion Hallway

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "on"

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway
        brightness_pct: "{{ 20 if is_state('binary_sensor.node_17', 'on') else 0 }}"

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/hallway'
        payload: "{{ 1 if is_state('binary_sensor.node_17', 'on') else 0 }}"
