###########################################################################################
#
# BEDROOM CONTROL LIGHTS BASED ON SENSOR AND DOOR SENSOR
#
###########################################################################################

- alias: "Motion Detection - Bedroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_14 # Motion Bedroom

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_daytime
      state: "on"

  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_all
        brightness_pct: >-
          {% if (states.binary_sensor.node_12.state) == "on" and (states.binary_sensor.node_14.state) == 'on' %} 20
          {% elif (states.binary_sensor.node_12.state) == "off" and (states.binary_sensor.node_14.state) == 'on' %} 100
          {% else %} 0
          {% endif %}

    - service: switch.turn_on
      data:
        entity_id: switch.meek_bedroom
