###########################################################################################
#
# CONTROL BEDROOM LIGHTS WHEN DOOR SENSOR IS ON OR OFF
#
###########################################################################################

- alias: "Door Sensor - Bedroom Door Open Close"
  trigger:

    platform: state
    entity_id: binary_sensor.node_12

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: light.bedroom_all
      state: "on"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      #kelvin: 2800
      brightness_pct: >-
        {% if (states.binary_sensor.node_12.state) == 'on' and ((states.sensor.season.state) == 'autumn' or (states.sensor.season.state) == 'winter') %} 100
        {% elif (states.binary_sensor.node_12.state) == 'on' and ((states.sensor.season.state) == 'spring' or (states.sensor.season.state) == 'summer') %} 20
        {% else %} 100
        {% endif %}
