###########################################################################################
#
# BEDROOM CONTROL LIGHTS BASED ON SENSOR AND DOOR SENSOR
#
###########################################################################################

- alias: "Motion Detection - Bedroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_14 # Motion Bedroom

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_daytime
      state: "off"

  action:
    - service_template: "{{ 'switch.turn_on' if is_state('binary_sensor.node_14', 'on') else 'switch.turn_off' }}"
      entity_id: switch.meek_bedroom

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/bedroom'
        payload: "{{ 1 if is_state('binary_sensor.node_14', 'on') else 0 }}"
