###########################################################################################
# LIVINGROOM CONTROL LIGHT BASED ON SENSOR AND SCENE GOODNIGHT
###########################################################################################

- alias: "Motion Detection - Livingroom On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_19 # Motion Livingroom

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "on"

    - condition: state
      entity_id: switch.meek_wall
      state: "off"

    - condition: state
      entity_id: switch.meek_window
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

  action:
    - service: light.turn_on
      data_template:
        entity_id: light.livingroom_all
        brightness_pct: "{{ 20 if is_state('binary_sensor.node_19', 'on') else 0 }}"

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/livingroom'
        payload: "{{ 1 if is_state('binary_sensor.node_19', 'on') else 0 }}"
