###########################################################################################
#
# TOILET CONTROL LIGHT BASED ON SENSOR AND SCENE GOODNIGHT
#
###########################################################################################

- alias: "Motion Detection - Toilet On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_20 # Motion Toilet

  condition:
    condition: state
    entity_id: switch.mqtt_scene_goodnight
    state: "off"

  action:
    - service: light.turn_on
      data_template:
        entity_id: light.toilet_all
        brightness_pct: "{{ 20 if is_state('binary_sensor.node_20', 'on') else 0 }}"

    - service_template: >-
        {% if (states.binary_sensor.node_20.state) == 'on' %} switch.turn_on
        {% else %}  switch.turn_off
        {% endif %}
      entity_id: switch.meek_bathroom

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/toilet'
        payload: "{{ 1 if is_state('binary_sensor.node_20', 'on') else 0 }}"
