###########################################################################################
# CONTROL LIGHT KITCHEN WHEN GOODNIGHT SCENE IS NOT ACTIVE
###########################################################################################

- alias: "Motion Detection - Kitchen On Off"
  trigger:

    platform: state
    entity_id: binary_sensor.node_16 # Motion Kitchen

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_daytime
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_cooking
      state: "off"

  action:
    - service_template: "{{ 'switch.turn_on' if is_state('binary_sensor.node_16', 'on') else 'switch.turn_off' }}"
      entity_id:
        - switch.meek_kitchen_seeling
        - switch.meek_kitchen_sink
        - switch.meek_cooking

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/kitchen'
        payload: "{{ 1 if is_state('binary_sensor.node_16', 'on') else 0 }}"
