###########################################################################################
#
# CONTROL LIGHT KITCHEN WHEN GOODNIGHT SCENE IS ACTIVE
#
###########################################################################################

- alias: "Motion Detection - Kitchen On Off Goodnight Scene Active"
  trigger:

    platform: state
    entity_id: binary_sensor.node_16 # Motion Kitchen

  condition:
    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "on"

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

    - condition: state
      entity_id: sensor.holiday
      state: "Nothing"

  action:
#    - service: light.turn_on
#      data_template:
#        entity_id:
#          - light.kitchen_all
#          - light.sink_all
#        brightness_pct: "{{ 20 if is_state('binary_sensor.node_16', 'on') else 0 }}"

    - service_template: >-
        {% if (states.binary_sensor.node_16.state) == 'on' %} switch.turn_on
        {% else %} switch.turn_off
        {% endif %}
      entity_id:
        - switch.meek_kitchen_seeling
        - switch.meek_kitchen_sink

    - service: mqtt.publish
      data_template:
        topic: 'homeassistant/motion/kitchen'
        payload: "{{ 1 if is_state('binary_sensor.node_16', 'on') else 0 }}"
