- alias: 'Notification - RDW - Terugroep verzoek'
  trigger:
    - platform: state
      entity_id: sensor.toyota_aygo_recall
      to: 'True'
  action:
    - service: notify.ha_email
      data_template:
        title: "HA - Terugroepactie"
        message: "Er is een terugroepactie uitgevaardigd voor de auto. Maak een afspraak bij de garage om het probleem te verhelpen."
