- alias: "Notification - RDW - APK vervaldatum"
  trigger:
  
    platform: template
    value_template: "{{ ((as_timestamp(strptime(states('sensor.toyota_aygo_expdate'), '%d %b %Y')) / 86400) | int) == ((as_timestamp(strptime(states('sensor.date'), '%Y-%m-%d')) / 86400) | int) + 21 }} }}"

  action:
    service: notify.ha_email
    data_template:
      title: "HA - APK Keuring loop af"
      message: "De APK keuring verloopt op {{ states.sensor.toyota_aygo_expdate.state }}. Plan een APK keuring bij de garage."
