###########################################################################################
#
# NOTIFY WHEN INSURANCE HAS BEEN EXPIRED FOR THE CAR OF MY SISTER
#
###########################################################################################

- alias: "Notification - RDW - Verzekering"
  trigger:

    platform: state
    entity_id: sensor.toyota_aygo_insured
    to: "false"

  action:
    service: notify.ha_email
    data_template:
      title: "HA - Auto verzekering verlopen"
      message: "De auto is niet verzekerd! Sluit een autoverzekering af voordat je ermee de weg op gaat."
