###########################################################################################
# NOTIFY WHEN INSURANCE HAS BEEN EXPIRED FOR THE CAR OF MY SISTER
###########################################################################################

- alias: "Notification - RDW - Verzekering"
  trigger:

    platform: state
    entity_id: sensor.toyota_aygo_insured
    to: "false"

  action:
    service: script.pushover_engine
    data_template:
      message: "De auto is niet verzekerd! Sluit een autoverzekering af voordat je ermee de weg op gaat."
      priority: "0"
      sound: "bike"
      title: "HA - Auto verzekering verlopen"
