  >-
  {%- macro dark_outside() -%}
  {{ [
      'It is pretty dark outside. I will turn on the outside lights now.',
      'It is a little past Sunset. Time to turn on the outside lights. I am on it.',
      'I will switch on the outside lights. It is getting dark outside.',
      'Time to turn on the front lights. I will take care of it.',
      'Switching to night mode! '
  ]|random }}
  {%- endmacro -%}

  {%- macro inside_weather() -%}
  Inside the house, it is {{ states.sensor.entryway_thermostat_temperature }} degrees with around {{ states('sensor.entryway_thermostat_humidity') }} percent humidity.
  {%- endmacro -%}

  {%- macro outside_weather() -%}
  Outside, it is going to be {{ states('sensor.dark_sky_daily_summary') }}
  {%- endmacro -%}


  {%- macro holiday() -%}
  {% if states.sensor.holiday.state != '' %}
      Today is {{ states.sensor.birthday.state }}.
  {% endif %}
  {%- endmacro -%}

  {% macro inspirational_quote() %}
      {% set inspirational_quote = [
      "and one more thing, Life is about making an impact, make it a positive one. ",
      "and one more thing, Whatever the mind of man can conceive and believe, it can achieve. ",
      "and one more thing, Strive not to be a success, but rather to be of value. ",
      "and one more thing, I attribute my overall success to never giving or taking an excuse. ",
      "and one more thing, You miss one hundred percent of the shots you don’t take. ",
      "and one more thing, The most difficult thing is the decision to act, the rest is merely tenacity. ",
      "and one more thing, Every strike brings me closer to the next home run. ",
      "and one more thing, Too many of us are not living our dreams because we are living our fears. ",
      "and one more thing, Challenges are what make life interesting and overcoming them is what makes life meaningful. ",
      "and one more thing, If you want to lift yourself up, lift up someone else. "
      "and one more thing, Be nice to others and nice things will happen to you."
      ] %}
      {{inspirational_quote|random}}
  {% endmacro %}

  {# ********************************************* #}
  {#  ******** Start the Speech routines ********  #}
  {# ********************************************* #}

  {% if call_no_announcement != 1 %}
  {% if now().strftime('%H')|int < 12 and now().strftime('%H')|int > 6 %}
      Good morning.
  {% elif now().strftime('%H')|int >= 12 and now().strftime('%H')|int < 17 %}
      Good afternoon.
  {% else %}
      Good evening.
  {% endif %}
  {% endif %}

  {# Called from Annoucenments #}
  {{ personarriving }}

  {% if call_inside_weather == 1 %}
  {{ inside_weather() }}
  {% endif %}

  {% if call_outside_weather == 1 and is_state('sun.sun', 'above_horizon') %}
  {{ outside_weather() }}
  {% endif %}

  {% if call_dark_outside == 1 %}
  {{ dark_outside() }}
  {% endif %}
