- alias: 'Control - Bathroom Lights Are On'
  trigger:
  - entity_id: binary_sensor.node_15
    platform: state
    to: 'off'
    for:
      minutes: 5

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off'

    - condition: state
      entity_id: switch.newkaku_01616a32_a
      state: 'on'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.newkaku_01616a32_a
      
    - service: notify.pushover
      data_template:
        message: "Turned off bathroom switch and light"
        title: "HA System"
