- alias: 'Motion Detection - Livingroom On Off'
  trigger:
    platform: state
    entity_id: binary_sensor.node_19

  condition:
    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off'

    - condition: state
      entity_id: switch.newkaku_0114ef92_b
      state: 'off'

    - condition: state
      entity_id: switch.newkaku_0114ef92_c
      state: 'off' 

  action:
    service: light.turn_on
    entity_id: light.livingroom_all
    data_template:
      kelvin: 2700
      brightness_pct: >-
        {% if (states.binary_sensor.node_19.state) == 'on' %} 20
        {% elif (states.binary_sensor.node_19.state) == 'off' %} 0
        {% endif %}
