- platform: mqtt
  name: "Bathroom 4"
  schema: json
  command_topic: "milight/0xAAAD/rgb_cct/4"
  state_topic: "milight/states/0xAAAD/rgb_cct/4"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../package/templates/light_effects.yaml

- platform: mqtt
  name: "Bathroom 3"
  schema: json
  command_topic: "milight/0xAAAD/rgb_cct/3"
  state_topic: "milight/states/0xAAAD/rgb_cct/3"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../package/templates/light_effects.yaml 

- platform: mqtt
  name: "Bathroom 2"
  schema: json
  command_topic: "milight/0xAAAD/rgb_cct/2"
  state_topic: "milight/states/0xAAAD/rgb_cct/2"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../package/templates/light_effects.yaml

- platform: mqtt
  name: "Bathroom 1"
  schema: json
  command_topic: "milight/0xAAAD/rgb_cct/1"
  state_topic: "milight/states/0xAAAD/rgb_cct/1"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../package/templates/light_effects.yaml

- platform: mqtt
  name: "Bathroom All"
  schema: json
  command_topic: "milight/0xAAAD/rgb_cct/0"
  state_topic: "milight/states/0xAAAD/rgb_cct/0"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../package/templates/light_effects.yaml 

