###########################################################################################
#
# LIVINGROOM AND DINGROOM CONTROL LIGHTS BASED ON LUX LEVEL
#
###########################################################################################

- alias: "Control - Lux Control Livingroom On"
  trigger:

    - platform: state
      entity_id: sensor.node_19_luminance

  condition:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"

    - condition: state
      entity_id: switch.mqtt_lux_level_low
      state: "off"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

    - condition: numeric_state
      entity_id: sensor.node_19_luminance
      below: 180

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

#    - condition: or
#      conditions:
#        - condition: state
#          entity_id: binary_sensor.node_18 # Motion Diningroom
#          state: 'on'
#          for:
#            seconds: 25

#        - condition: state
#          entity_id: binary_sensor.node_19 # Motion Livingroom
#          state: 'on'
#          for:
#            seconds: 25

  action:
    - service: light.turn_on
      entity_id:
        - light.livingroom_all
        - light.dressoir_all
      data:
        transition: 10
        brightness_pct: 75

    - service: switch.turn_on
      entity_id: switch.mqtt_lux_level_low

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_lux_evening_on: "true"

- alias: "Control - Lux Control Livingroom Off"
  trigger:

    - platform: state
      entity_id: sensor.node_19_luminance

  condition:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"

    - condition: numeric_state
      entity_id: sensor.node_19_luminance
      above: 181

    - condition: state
      entity_id: switch.mqtt_lux_level_low
      state: "on"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

    - condition: state
      entity_id: switch.mqtt_scene_guests
      state: "off"

  action:
    - service: light.turn_on
      entity_id:
        - light.livingroom_all
        - light.dressoir_all
      data:
        transition: 10
        brightness_pct: 0

    - service: switch.turn_off
      entity_id: switch.mqtt_lux_level_low

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_lux_evening_off: "true"
