- alias: Control - Turn on Zwave 4 and 5
  trigger:
    - entity_id: group.group_family
      platform: state
      to: home

  condition:
    - condition: state
      entity_id: group.group_family
      state: home

  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.node_5_switch
          - switch.node_6_switch
          - switch.node_7_switch

- alias: Control - Turn off Zwave 4 and 5
  trigger:
    - entity_id: group.group_family
      platform: state
      to: not_home

  condition:
    - condition: state
      entity_id: group.group_family
      state: not_home

  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.node_5_switch
          - switch.node_6_switch
          - switch.node_7_switch
