- platform: mqtt
  name: "Balcony"
  schema: json
  command_topic: "milight/0xAAA4/rgb_cct/1"
  state_topic: "milight/states/0xAAA4/rgb_cct/1"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: [0, 1, 2, 3, 4 ,5, 6, 7, 8]
