- platform: mqtt
  name: "Bedroom All"
  schema: json
  command_topic: "milight/0xAABA/rgb_cct/1"
  state_topic: "milight/states/0xAABA/rgb_cct/1"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Bedroom 1"
  schema: json
  command_topic: "milight/0xAAAA/rgb_cct/1"
  state_topic: "milight/states/0xAAAA/rgb_cct/1"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Bedroom 2"
  schema: json
  command_topic: "milight/0xAAAA/rgb_cct/2"
  state_topic: "milight/states/0xAAAA/rgb_cct/2"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml 

- platform: mqtt
  name: "Bedroom 3"
  schema: json
  command_topic: "milight/0xAAAA/rgb_cct/3"
  state_topic: "milight/states/0xAAAA/rgb_cct/3"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml 

- platform: mqtt
  name: "Bedroom 4"
  schema: json
  command_topic: "milight/0xAAAA/rgb_cct/4"
  state_topic: "milight/states/0xAAAA/rgb_cct/4"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Bedroom 5"
  schema: json
  command_topic: "milight/0xAAAB/rgb_cct/1"
  state_topic: "milight/states/0xAAAB/rgb_cct/1"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Bedroom 6"
  schema: json
  command_topic: "milight/0xAAAB/rgb_cct/2"
  state_topic: "milight/states/0xAAAB/rgb_cct/2"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml 

