- platform: mqtt
  name: "Sink All"
  schema: json
  command_topic: "milight/0xAAA1/rgb_cct/0"
  state_topic: "milight/states/0xAAA1/rgb_cct/0"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Sink 1"
  schema: json
  command_topic: "milight/0xAAA1/rgb_cct/1"
  state_topic: "milight/states/0xAAA1/rgb_cct/1"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Sink 2"
  schema: json
  command_topic: "milight/0xAAA1/rgb_cct/2"
  state_topic: "milight/states/0xAAA1/rgb_cct/2"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

- platform: mqtt
  name: "Sink 3"
  schema: json
  command_topic: "milight/0xAAA1/rgb_cct/3"
  state_topic: "milight/states/0xAAA1/rgb_cct/3"
  qos: 1
  optimistic: false
  retain: true
  brightness: true
  rgb: true
  color_temp: true
  effect: true
  effect_list: !include ../../config/templates/light_effects.yaml

