###########################################################################################
# CONTROL CIRCADIAN LIGHTS AUTOMATION WHEN THERE IS A HOLIDAY OR NOT
###########################################################################################

- alias: "Control - Circardian"
  trigger:

    - platform: state
      entity_id: sensor.holiday

  condition:
    - condition: state
      entity_id: sensor.holiday
      state: "Nothing"

    - condition: state
      entity_id: group.circadian_lights
      state: "off"

  action:
    service_template: "{{ 'homeassistant.turn_on' if is_state('sensor.holiday', 'Nothing') else 'homeassistant.turn_off' }}"
    entity_id: group.circadian_lights
