###########################################################################################
# AUTO BACKUP
# https://github.com/sabeechen/hassio-google-drive-backup
###########################################################################################
---
auto_purge: "true"
