###########################################################################################
# CIRCADIAN LIGHTING
# https://github.com/claytonjn/hass-circadian_lighting
###########################################################################################
---
max_colortemp: 3800
