###########################################################################################
#
# MONITOR BEACON
#
# https://github.com/andrewjfreyer/monitor/blob/master/support/README.md
#
###########################################################################################
---
platform: mqtt
devices:
andrew_first_floor: 'beacon/hallway/peter_iphone/device_tracker'

---
platform: mqtt
devices:
andrew_first_floor: 'beacon/hallway/kay_iphone/device_tracker'
