###########################################################################################
#
# MONITOR BEACON
#
# https://github.com/andrewjfreyer/monitor
#
###########################################################################################
---
platform: mqtt
devices:
  peter_iphone_beacon_tracker: "HABeacon/Hallway/peter_iphone/device_tracker"
  kay_iphone_beacon_tracker: "HABeacon/Hallway/kay_iphone/device_tracker"
source_type: "bluetooth"
