###########################################################################################
# FRONTEND
# https://www.home-assistant.io/integrations/frontend/
###########################################################################################
---
themes: !include_dir_merge_named /config/compontents/themes
