###########################################################################################
#
# HOMEASSSTANT
#
# https://www.home-assistant.io/docs/configuration/basic/
#
###########################################################################################
---
customize: !include_dir_merge_named /config/package/customize/
customize_glob: !include_dir_merge_named /config/package/customize_global/
#  fan.*:
#    custom_ui_state_card: state-card-custom-fanspeed
auth_providers:
  - type: homeassistant
whitelist_external_dirs:
  - /config