###########################################################################################
#
# HOMEASSSTANT
#
# https://www.home-assistant.io/docs/configuration/basic/
#
###########################################################################################
---
#customize: !include_dir_merge_named /config/package/customize/
customize: !include_dir_named /config/package/customize/
customize_glob: !include_dir_merge_named /config/package/customize_global/
whitelist_external_dirs:
  - /config
auth_providers:
  - type: trusted_networks
    trusted_networks:
      - 127.0.0.1
      - !secret local_network
    trusted_users:
      127.0.0.1:
        - !secret user_id1
        - !secret user_id2
        - !secret user_id3
      !secret local_network:
        - !secret user_id1
        - !secret user_id2
        - !secret user_id3
    allow_bypass_login: true
  - type: homeassistant
