###########################################################################################
#
# HOMEASSSTANT
#
# https://www.home-assistant.io/docs/configuration/basic/
#
###########################################################################################
---
customize: !include_dir_merge_named /config/package/customize/
customize_glob: !include_dir_merge_named /config/package/customize_global/
whitelist_external_dirs:
  - /config
auth_providers:
  - type: trusted_networks
    trusted_networks:
      - 127.0.0.1
      - !secret local_network
  - type: homeassistant
