###########################################################################################
#
# HOMEKIT
#
# https://www.home-assistant.io/integrations/homekit/
#
###########################################################################################
---
auto_start: "false"
filter:
  include_domains:
    - climate
  include_entities:
    - input_number.fullykiosk_brightness_slider

# Motion Sensors
    - binary_sensor.node_14 # Motion Bedroom
    - binary_sensor.node_15 # Motion Bathroom
    - binary_sensor.node_16 # Motion Kitchen
    - binary_sensor.node_17 # Motion Hallway
    - binary_sensor.node_18 # Motion Diningroom
    - binary_sensor.node_19 # Motion Livingroom
    - binary_sensor.node_20 # Motion Toilet

# Nest Protect
    - sensor.bedroom_nest_protect_co_status
    - sensor.bedroom_nest_protect_smoke_status
    - sensor.dining_room_nest_protect_co_status
    - sensor.dining_room_nest_protect_smoke_status
    - sensor.living_room_nest_protect_co_status
    - sensor.living_room_nest_protect_smoke_status
    - sensor.nest_protect_bedroom_status_homekit
    - sensor.nest_protect_diningroom_status_homekit
    - sensor.nest_protect_livingroom_status_homekit

# Lights
    - light.livingroom_all
    - light.dressoir_all
    - light.hallway
    - light.balcony
    - light.kitchen_all
    - light.sink_all
    - light.bedroom_all
    - light.bathroom_all
    - light.toilet_all
    - light.nanoleaf
    - light.browser_890da611_f381e6e1
# Scenes
    - switch.mqtt_scene_sleeping
    - switch.mqtt_scene_sexy
    - switch.mqtt_scene_kodi
    - switch.mqtt_scene_goodnight
    - switch.mqtt_scene_appletv
    - switch.mqtt_scene_daytime
    - switch.mqtt_scene_tv
    - switch.mqtt_scene_evening
    - switch.mqtt_scene_disco
    - switch.mqtt_scene_cooking
    - switch.mqtt_kay_learning
    - switch.mqtt_disable_nest_control
# Logitech Activities
    - switch.airplay
    - switch.kodi
    - switch.tv
    - switch.appletv
# NEST
    - climate.entryway
# MEEK Switches
#    - switch.meek_kitchen_seeling
#    - switch.meek_kitchen_sink
#    - switch.meek_hallway
#    - switch.meek_bedroom
#    - switch.meek_bathroom
#    - switch.meek_toilet
#    - switch.meek_cooking
#    - switch.meek_dressoir
#    - switch.meek_livingroom
# Device trackers
    - binary_sensor.manual_kay_home
    - binary_sensor.manual_peter_home
# Temperature sensors
    - sensor.node_11_temperature
    - sensor.node_13_temperature
    - sensor.node_14_temperature
    - sensor.node_15_temperature
    - sensor.node_16_temperature
    - sensor.node_17_temperature
    - sensor.node_18_temperature
    - sensor.node_19_temperature
    - sensor.node_20_temperature
# KaKu SWITCHES
#    - switch.newkaku_0114ef92_b
#    - switch.newkaku_0114ef92_c
#    - switch.newkaku_011fad02_b
#    - switch.newkaku_011fad02_c
#    - switch.newkaku_011fdd46_b
#    - switch.newkaku_011fdd46_c
#    - switch.newkaku_01074522_a
#    - switch.newkaku_01616a32_a
#    - switch.newkaku_014e5906_a

  exclude_entities:
    - binary_sensor.bedroom_nest_protect_online
    - binary_sensor.dining_room_nest_protect_online
    - binary_sensor.living_room_nest_protect_online
    - binary_sensor.entryway_thermostat_has_leaf
    - binary_sensor.entryway_thermostat_online
    - binary_sensor.imac_peter
    - binary_sensor.milight_hub
    - binary_sensor.toshiba_laptop
    - binary_sensor.asingaborg_away
