###########################################################################################
# LOGGER
# https://www.home-assistant.io/integrations/logger/
# critical < fatal < error < warning < warn < info < debug < notset
###########################################################################################
---
default: error
logs:
  homeassistant.components.websocket_api: fatal
  homeassistant.components.zwave: warning
  homeassistant.helpers.service: warning
  homeassistant.components.pushover.notify: warning
  homeassistant.loader: fatal
  homeassistant.components.alexa.state_report: fatal
  #custom_components.alexa_media: debug
