###########################################################################################
# NEXTCLOUD
# https:unknown
###########################################################################################
---
url: !secret nextcloud_url
username: !secret nextcloud_user
password: !secret nextcloud_password
