###########################################################################################
#
# DARK SKY
#
# https://www.home-assistant.io/integrations/darksky/
#
###########################################################################################
---
platform: darksky
api_key: !secret darsky_apikey
mode: daily
latitude: !secret latitude
longitude: !secret longitude
