###########################################################################################
# BUIENRADAR
# https://www.home-assistant.io/integrations/sensor.buienradar/
###########################################################################################
---
platform: buienradar
name: "buienradar"
