- alias: Door Sensor - Bedroom Door Open Lights to 20
  trigger:
    platform: state
    entity_id: binary_sensor.node_12
    to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - condition: state
      entity_id: light.bedroom_all
      state: 'on'

  action:
    service: light.turn_on
    entity_id: light.bedroom_all
    data:
      kelvin: 4700
      brightness_pct: 20

- alias: Door Sensor - Bedroom Door Closed Lights to 100
  trigger:
    platform: state
    entity_id: binary_sensor.node_12
    to: 'off'

  condition:                                                                                               
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - condition: state
      entity_id: light.bedroom_all
      state: 'on'

  action:
    service: light.turn_on
    entity_id: light.bedroom_all
    data:
      kelvin: 4700
      brightness_pct: 100
