- alias: 'Notification - Door Open'
  trigger:
    - platform: state
      entity_id: sensor.node_12_access_control,
                 sensor.node_11_access_control,
                 sensor.node_10_access_control
      to: '22'

  action:
  - service: notify.pushover
    data_template:
      message: " {{ trigger.from_state.attributes.friendly_name }} door is open"
      title: "HA Security System"

- alias: 'Notification - Door Close'
  trigger:
    - platform: state
      entity_id: sensor.node_12_access_control,
                 sensor.node_11_access_control,
                 sensor.node_10_access_control
      to: '23'

  action:
  - service: notify.pushover
    data_template:
      message: " {{ trigger.from_state.attributes.friendly_name }} door is closed"
      title: "HA Security System"
