###########################################################################################
#
# INPUT_BOOLEAN
#
# https://www.home-assistant.io/integrations/input_boolean/
#
###########################################################################################
---
nest_disable_control:
  initial: "off"
