###########################################################################################
#
# NOTIFY WHEN THERE IS A BAD LOGIN
#
###########################################################################################

- alias: "Notification - Goto Work"
  trigger:

    platform: time_pattern
    minutes: "/1"
      
  condition:
    condition: template
    value_template: "{{ as_timestamp(now()) | int < (as_timestamp(states.calendar.werk.attributes.start_time)-3600) | int }}"

  action:
    service: script.pushover_engine
    data_template:
      message: "1 Uur voor naar werk gaan, test voor automatisering"
      priority: "0"
      sound: "bike"
      title: "HA Test 1 uur van te voren werken"
