- alias: "Notification - Random Door Open"
  initial_state: "false"
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.node_10
        - binary_sensor.node_12
        - sensor.fibaro_frontdoor_custom_sensor
        - sensor.fibaro_imac_custom_sensor
      to: "on"

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ trigger.from_state.attributes.friendly_name }} door is open"
        priority: 0
        sound: bike
        title: "HA Notify Engine"

- alias: "Notification - Random Door Close"
  initial_state: "false"
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.node_10
        - binary_sensor.node_12
        - sensor.fibaro_frontdoor_custom_sensor
        - sensor.fibaro_imac_custom_sensor 
      to: "off"

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ trigger.from_state.attributes.friendly_name }} door is closed"
        priority: 0
        sound: bike
        title: "HA Notify Engine"
