- alias: 'Notification - Peter Left or Arrive Home'
  trigger:
  - entity_id: device_tracker.geofency_peter
    platform: state

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ 'Peter arrived home' if is_state('device_tracker.geofency_peter', 'home') else 'Peter left home.' }}"
        priority: 0
        sound: bike
        title: "HA Notify Engine"
