###########################################################################################
#
# NOTIFY WHEN DOORS OPEN OR CLOSE
#
###########################################################################################

- alias: "Notification - Random Door Open Close"
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.node_21 # Sensor Diningroom Door
  #    - binary_sensor.node_12 # Sensor Bedroom Door
  #    - binary_sensor.fibaro_frontdoor_custom_sensor
  #    - binary_sensor.fibaro_imac_custom_sensor
  action:
    service: script.pushover_engine
    data_template:
      message: >-
        {{ trigger.from_state.attributes.friendly_name }} is {{ 'open' if trigger.to_state.state == 'on' else 'closed' }}
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
