###########################################################################################
#
# NOTIFY WHEN THERE IS MOTION AND NOBODY IS HOME
#
###########################################################################################

- alias: "Motion Detection - Notification Nobody Home"
  trigger:

    - platform: state
      entity_id:
        - binary_sensor.node_15 # Motion Bathroom
        - binary_sensor.node_20 # Motion Toilet
        - binary_sensor.node_21 # Sensor Diningroom Door
        - binary_sensor.node_12 # Sensor Bedroom Door
        - binary_sensor.node_14 # Motion Bedroom
        - binary_sensor.node_16 # Motion Kitchen
        - binary_sensor.node_17 # Motion Hallway
        - binary_sensor.node_18 # Motion Diningroom
        - binary_sensor.node_19 # Motion Livingroom
      to: "on"

    - platform: state
      entity_id:
        - sensor.node_13_access_control
        - sensor.node_11_access_control
      to: "22"

  condition:
    condition: state
    entity_id: binary_sensor.sensor_manual_family_home
    state: "off"

  action:
    service: script.pushover_engine
    data_template:
      message: "registered motion {{ trigger.from_state.attributes.friendly_name  }}"
      priority: "2"
      sound: "pushover"
      title: "HA Security ALERT"
