###########################################################################################
#
# NOTIFY WHEN THERE IS A BAD LOGIN
#
###########################################################################################

- alias: "Notification - Goto Work"
  trigger:

    platform: time_pattern
    minutes: "/1"

  condition:
    condition: template
    value_template: "{{ as_timestamp(utcnow()) | int > (as_timestamp(states.calendar.werk.attributes.start_time)-3600) | int }}"

  action:
    service: script.pushover_engine
    data_template:
      message: "1 Hour before work. Prepare!"
      priority: "0"
      sound: "bike"
      title: "HA 1 Hour work"
