- alias: "Notification - Peter Left or Arrive Home"
  trigger:
  
    platform: state
    entity_id: device_tracker.geofency_peter

  action:
    service: script.pushover_engine
    data_template:
      message: "{{ 'Peter arrived home' if is_state('device_tracker.geofency_peter', 'home') else 'Peter left home.' }}"
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
