###########################################################################################
#
# NOTIFY WHEN A DEVICE IS (DIS)CONNECTED
#
###########################################################################################

- alias: "Notification - Device (dis)connected"
  trigger:

    platform: state
    entity_id:
      - binary_sensor.resillio
      - binary_sensor.milight_hub
    to: "off"

  action:
    service: script.pushover_engine
    data_template:
      message: "{{ trigger.from_state.attributes.friendly_name }} disconnected"
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"

- alias: "Notification - Device connected"
  trigger:

    platform: state
    entity_id:
      - binary_sensor.resillio
      - binary_sensor.milight_hub
    to: "on"

  action:
    service: script.pushover_engine
    data_template:
      message: "{{ trigger.from_state.attributes.friendly_name }} connected again"
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
