###########################################################################################
#
# NOTIFY WHEN PETER IS LEFT OR ARRIVE HOME
#
###########################################################################################

- alias: "Notification - Peter Left or Arrive Home"
  trigger:

    platform: state
    entity_id:
#      - device_tracker.1717fe36_3c70_4599_963c_b70b6ee95eba
#      - device_tracker.peter_iphone_geofency
      - device_tracker.peter_iphone_ha

  action:
    service_template: >-
      {%- if trigger.from_state.state == trigger.to_state.state -%}
        script.pushover_engine
      {%- else -%}
        script.none
      {%- endif -%}
    data_template:
      message: >-
        {% if trigger.to_state.state == 'home' %}
          Peter arrived home
        {% else %}
          Peter left home
        {% endif %}
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
