- alias: "Notification - Login Failure"
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.http_login') != 'unknown' }}"

  action:
    service: script.pushover_engine
    data_template:
      message: "There is a bad login registered on Home Assistant"
      priority: 2
      sound: bike
      title: "HA Security ALERT"
