###########################################################################################
#
# NOTIFY WHEN DOORS OPEN OR CLOSE
#
###########################################################################################

- alias: "Notification - Random Door Open Close"
  initial_state: "false"
  trigger:

    platform: state
    entity_id:
      - binary_sensor.node_21
      - binary_sensor.node_12
      - sensor.fibaro_frontdoor_custom_sensor
      - sensor.fibaro_imac_custom_sensor

  action:
    service: script.pushover_engine
    data_template:
      message: >-
        {% if trigger.to_state.state == 'on' %}
          {{ trigger.from_state.attributes.friendly_name}} is open
        {% else %}
          {{ trigger.from_state.attributes.friendly_name}} is closed
        {% endif %}
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
