###########################################################################################
#
# NOTIFY WHEN PETER IS LEFT OR ARRIVE HOME
#
###########################################################################################

- alias: "Notification - Peter Left or Arrive Home"
  trigger:

    platform: state
    entity_id:
      - device_tracker.peter_iphone_beacon_tracker
      - device_tracker.peter_iphone_ha

  action:
    service: script.pushover_engine
    data_template:
      message: >-
        {% if trigger.to_state.state == 'home' %}
          Peter arrived home - {{ trigger.from_state.attributes.friendly_name }}
        {% else %}
          Peter left home - {{ trigger.from_state.attributes.friendly_name }}
        {% endif %}
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
