- alias: "Motion Detection - Notification Nobody Home"
  trigger:
  
    - platform: state
      entity_id: 
        - binary_sensor.node_15
        - binary_sensor.node_20
        - binary_sensor.node_10
        - binary_sensor.node_12
        - binary_sensor.node_14
        - binary_sensor.node_16
        - binary_sensor.node_17
        - binary_sensor.node_18
        - binary_sensor.node_19
      to: "on"

    - platform: state
      entity_id: 
        - sensor.node_13_access_control
        - sensor.node_11_access_control
      to: "22"

  condition:
    condition: state
    entity_id: binary_sensor.sensor_manual_family_home
    state: "off" 

  action:
    service: script.pushover_engine
    data_template:
      message: "registered motion {{ trigger.from_state.attributes.friendly_name  }}"
      priority: "2"
      sound: "pushover"
      title: "HA Security ALERT"