###########################################################################################
#
# NOTIFY WHEN KAY IS LEFT OR ARRIVE HOME
#
###########################################################################################

- alias: "Notification - Kay Left or Arrive Home"
  trigger:

    platform: state
    entity_id:
      - device_tracker.kay_iphone_geofency
      - device_tracker.kay_iphone_beacon_tracker

  action:
    service: script.pushover_engine
    data_template:
      message: >-
        {% if trigger.to_state.state == 'home' %}
          Kay arrived home - { trigger.from_state.attributes.friendly_name}}
        {% else %}
          Kay left home - { trigger.from_state.attributes.friendly_name}}
        {% endif %}
      priority: "0"
      sound: "bike"
      title: "HA Notify Engine"
