###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Balcony"
  trigger:

    platform: state
    entity_id: switch.meek_balcony

  action:
    service: light.turn_on
    data_template:
      entity_id: light.balcony
      brightness_pct: >-
        {% if states('switch.meek_balcony') == 'on' and states('switch.mqtt_scene_goodnight') == 'on' %} 20
        {% elif states('switch.meek_balcony') == 'on' and states('switch.mqtt_scene_goodnight') == 'off' %} 100
        {% else %} 0
        {% endif %}
