###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Bathroom"
  trigger:

    platform: state
    entity_id: switch.meek_bathroom

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bathroom_all
      #kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.meek_bathroom', 'on') else 0 }}"
