###########################################################################################
#
# CONTROL LIGHT BEDROOM WHEN DAYTOME SCENE IS OFF
#
###########################################################################################

- alias: "Switch - Meek Bedroom"
  trigger:

    platform: state
    entity_id: switch.meek_bedroom

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      brightness_pct: >-
        {% if states('switch.meek_bedroom') == 'on' and states('binary_sensor.node_12') == 'on' %} 20
        {% elif states('switch.meek_bedroom') == 'on' and states('binary_sensor.node_12') == 'off' %} 100
        {% else %} 0
        {% endif %}
