###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Balcony"
  trigger:

    platform: state
    entity_id: switch.newkaku_011fdd46_b

  action:
    service: light.turn_on
    data_template:
      entity_id: light.balcony
      kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.newkaku_011fdd46_b', 'on') else 0 }}"
