- alias: 'Switch - Kitchen On Off'
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fad02_b

  action:
    - service: light.turn_on
      entity_id: light.sink_all
      data_template:
        brightness_pct: >-
          {% if (states.switch.newkaku_011fad02_b.state) == 'on' %} 100
          {% else %} 0
          {% endif %}
        kelvin: 4700

    - service: light.turn_on
      entity_id: light.kitchen_all
      data_template:
        brightness_pct: >-
          {% if (states.switch.newkaku_011fad02_b.state) == 'on' %} 100
          {% else %} 0
          {% endif %}
        kelvin: 4700
