###########################################################################################
# SWITCH CONTROL FOR TOILET
###########################################################################################

- alias: "Switch - Meek Toilet"
  trigger:

    platform: state
    entity_id: switch.meek_toilet

  action:
    service: light.turn_on
    data_template:
      entity_id: light.toilet_all
      brightness_pct: >-
        {% if states('switch.meek_toilet') == 'on' and states('switch.mqtt_scene_goodnight') == 'on' %} 40
        {% elif states('switch.meek_toilet') == 'on' and states('switch.mqtt_scene_goodnight') == 'off' %} 100
        {% else %} 0
        {% endif %}
