###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Sink"
  trigger:

    platform: state
    entity_id: switch.meek_kitchen_sink

  action:
    service: light.turn_on
    data_template:
      entity_id: light.sink_all
      #kelvin: 2800
      brightness_pct: >-
        {% if (states.switch.meek_kitchen_sink.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'on' %} 50
        {% elif (states.switch.meek_kitchen_sink.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} 100
        {% else %}0
        {% endif %}
