- alias: 'Switch - Kitchen On Off'
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fad02_b

  action:
    - service: light.turn_on
      entity_id: light.sink_all
      data_template:
        brightness_pct: "{{ 100 if is_state('switch.newkaku_011fad02_b', 'on') else 0 }}"
        kelvin: 4700

    - service: light.turn_on
      entity_id: light.kitchen_all
      data_template:
        brightness_pct: "{{ 100 if is_state('switch.newkaku_011fad02_b', 'on') else 0 }}"
        kelvin: 4700
