###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Sink"
  trigger:

    platform: state
    entity_id: switch.meek_kitchen_sink

  action:
    service: light.turn_on
    data_template:
      entity_id: light.sink_all
      #kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.meek_kitchen_sink', 'on') else 0 }}"
