###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meet Test"
  trigger:

    platform: state
    entity_id: switch.meek_test

  action:
    service: light.turn_on
    data_template:
      entity_id: light.dressoir_all
      brightness_pct: "{{ 100 if is_state('switch.meek_test', 'on') else 0 }}"
