- alias: 'Switch - Wall On Off'
  trigger:
    - platform: state
      entity_id: switch.newkaku_0114ef92_b

  action:
    service: light.turn_on
    entity_id: light.livingroom_wall
    data_template:
      brightness_pct: >-
        {% if (states.switch.newkaku_0114ef92_b.state) == 'on' %} 100
        {% else %} 0
        {% endif %}
      kelvin: 4700
