###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Seeling"
  trigger:

    platform: state
    entity_id: switch.meek_kitchen_seeling

  action:
    service: light.turn_on
    data_template:
      entity_id: light.kitchen_all
      #kelvin: 2800
      brightness_pct: >-
        {% if (states.switch.meek_kitchen_seeling.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'on' %} 20
        {% elif (states.switch.meek_kitchen_seeling.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} 100
        {% else %} 0
        {% endif %}
