- alias: 'Switch - Balcony On Off'
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fdd46_b

  action:
    service: light.turn_on
    entity_id: light.balcony
    data_template:
      brightness_pct: >-
        {% if (states.switch.newkaku_011fdd46_b.state) == 'on' %} 100
        {% else %} 0
        {% endif %} 
      kelvin: 2700
