- alias: 'Switch - Dressoir On Off'
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fdd46_c

  action:
    service: light.turn_on
    entity_id: light.dressoir_all
    data_template:
      kelvin: 4700
      brightness_pct: >-
        {% if (states.switch.newkaku_011fdd46_c.state) == 'on' %} 100
        {% else %} 0
        {% endif %}
