- alias: "Switch - Balcony On Off"
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fdd46_b

  action:
    service: light.turn_on
    entity_id: light.balcony
    data_template:
      brightness_pct: "{{ 100 if is_state('switch.newkaku_011fdd46_b', 'on') else 0 }}"
      kelvin: 4700
