###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Dressoir"
  trigger:

    platform: state
    entity_id: switch.meek_dressoir

  action:
    service: light.turn_on
    data_template:
      entity_id: light.dressoir_all
      brightness_pct: >-
        {% if states('switch.meek_dressoir') == 'on' and states('binary_sensor.node_21') == 'on' and states('switch.mqtt_scene_goodnight') == 'off' %} 10
        {% elif states('switch.meek_dressoir') == 'on' and states('binary_sensor.node_21') == 'on' and states('switch.mqtt_scene_goodnight') == 'on' %} 10
        {% elif states('switch.meek_dressoir') == 'on' and states('binary_sensor.node_21') == 'off' and states('switch.mqtt_scene_goodnight') == 'off' %} 100
        {% elif states('switch.meek_dressoir') == 'on' and states('binary_sensor.node_21') == 'off' and states('switch.mqtt_scene_goodnight') == 'on' %} 10
        {% else %} 0
        {% endif %}
