###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Dressoir"
  trigger:

    platform: state
    entity_id: switch.meek_dressoir

  action:
    service: light.turn_on
    data_template:
      entity_id: light.dressoir_all
      #kelvin: 2800
      brightness_pct: >-
        {% if (states.switch.meek_dressoir.state) == 'on' and (states.binary_sensor.node_21.state) == 'on' %} 20
        {% elif (states.switch.meek_dressoir.state) == 'on' and (states.binary_sensor.node_21.state) == 'off' %} 100
        {% else %} 0
        {% endif %}
