###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Liningroom"
  trigger:

    platform: state
    entity_id: switch.meek_livingroom

  action:
    service: light.turn_on
    data_template:
      entity_id: light.livingroom_all
      #kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.meek_livingroom', 'on') else 0 }}"
