- alias: "Switch - Hallway"
  trigger:
  
    platform: state
    entity_id: switch.newkaku_016138ba_a

  action:
    service: light.turn_on
    data_template:
      entity_id: light.hallway
      kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.newkaku_016138ba_a', 'on') else 0 }}"
