###########################################################################################
# SWITCH CONTROL FOR LIVINGROOM
###########################################################################################

- alias: "Switch - Meek Window"
  trigger:

    platform: state
    entity_id: switch.meek_window

  action:
    service: light.turn_on
    data_template:
      entity_id: light.livingroom_window
      brightness_pct: >-
        {% if states('switch.meek_window') == 'on' and states('switch.mqtt_scene_goodnight') == 'on' %} 10
        {% elif states('switch.meek_window') == 'on' and states('switch.mqtt_scene_goodnight') == 'off' %} 100
        {% else %} 0
        {% endif %}
