###########################################################################################
#
# SWITCH CONTROL FOR DININGROOM DRESSOIR
#
###########################################################################################

- alias: "Switch - Dressoir"
  trigger:

    platform: state
    entity_id: switch.newkaku_011fdd46_c

  action:
    service: light.turn_on
    data_template:
      entity_id: light.dressoir_all
      kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.newkaku_011fdd46_c', 'on') else 0 }}"
