- alias: "Switch - Bedroom"
  trigger:
  
    platform: state
    entity_id: switch.newkaku_01074522_a

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      kelvin: 2800
      brightness_pct: >-
        {% if (states.switch.newkaku_01074522_a.state) == 'on' and (states.binary_sensor.node_12.state) == 'on' %} 20
        {% elif (states.switch.newkaku_01074522_a.state) == 'on' and (states.binary_sensor.node_12.state) == 'off' %} 100
        {% else %} 0
        {% endif %}
