###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Toilet"
  trigger:

    platform: state
    entity_id: switch.meek_toilet

  action:
    service: light.turn_on
    data_template:
      entity_id: light.toilet_all
      #kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.meek_toilet', 'on') else 0 }}"
