###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meet Balcony"
  trigger:

    platform: state
    entity_id: switch.meek_baclony

  action:
    service: light.turn_on
    data_template:
      entity_id: light.balcony
      #kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.meek_baclony', 'on') else 0 }}"
