- alias: "Switch - Window"
  trigger:
  
    platform: state
    entity_id: switch.newkaku_0114ef92_c

  action:
    service: light.turn_on
    data_template:
      entity_id: light.livingroom_window
      kelvin: 4700
      brightness_pct: "{{ 100 if is_state('switch.newkaku_0114ef92_c', 'on') else 0 }}"
