###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Seeling"
  trigger:

    platform: state
    entity_id: switch.meek_kitchen_seeling

  action:
    service: light.turn_on
    data_template:
      entity_id: light.kitchen_all
      #kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.meek_kitchen_seeling', 'on') else 0 }}"
