###########################################################################################
# SWITCH CONTROL FOR BEDROOM
###########################################################################################

- alias: "Switch - Meek Bedroom"
  trigger:

    platform: state
    entity_id: switch.meek_bedroom

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      kelvin: 2800
      brightness_pct: >-
        {% if states('switch.meek_bedroom') == 'on'
           and states('binary_sensor.neo_bedroomdoor_custom_sensor') == 'on'
           and states('switch.mqtt_scene_goodnight') == 'off' %}
           20

        {% elif states('switch.meek_bedroom') == 'on'
           and states('binary_sensor.neo_bedroomdoor_custom_sensor') == 'off'
           and states('switch.mqtt_scene_goodnight') == 'off' %}
           100

        {% elif states('switch.meek_bedroom') == 'on'
           and states('binary_sensor.neo_bedroomdoor_custom_sensor') == 'on'
           and states('switch.mqtt_scene_goodnight') == 'on' %}
           0

        {% elif states('switch.meek_bedroom') == 'on'
           and states('binary_sensor.neo_bedroomdoor_custom_sensor') == 'off'
           and states('switch.mqtt_scene_goodnight') == 'on' %}
           0

        {% else %} 0
        {% endif %}
