###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Liningroom"
  trigger:

    platform: state
    entity_id: switch.meek_livingroom

  action:
    service: light.turn_on
    data_template:
      entity_id: light.livingroom_all
      brightness_pct: >-
        {% if states('switch.meek_livingroom') == 'on' and states('switch.mqtt_scene_goodnight') == 'on' %} 10
        {% elif states('switch.meek_livingroom') == 'on' and states('switch.mqtt_scene_goodnight') == 'off' %} 100
        {% else %} 0
        {% endif %}
