###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meek Sink"
  trigger:

    platform: state
    entity_id: switch.meek_kitchen_sink

  action:
    service_template: >-
      {% if (states.switch.meek_kitchen_sink.state) == 'on' and (states.sensor.holiday.state) == 'Christmas' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_christmas_turn_on
      {% elif (states.switch.meek_kitchen_sink.state) == 'on' and (states.sensor.holiday.state) == 'Halloween' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_halloween_turn_on
      {% elif (states.switch.meek_kitchen_sink.state) == 'on' and (states.sensor.holiday.state) == 'Kingsday' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_kingsday_turn_on
      {% elif (states.switch.meek_kitchen_sink.state) == 'on' and (states.sensor.holiday.state) == 'Birthday' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_birthday_turn_on
      {% elif (states.switch.meek_kitchen_sink.state) == 'on' and (states.sensor.holiday.state) == 'No holiday today' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} script.kitchen_turn_off
      {% endif %}
