###########################################################################################
#
# SWITCH CONTROL FOR BALCONY
#
###########################################################################################

- alias: "Switch - Meet Balcony"
  trigger:

    platform: state
    entity_id: switch.meek_balcony

  action:
    service: light.turn_on
    data_template:
      entity_id: light.balcony
      #kelvin: 2800
      brightness_pct: >-
        {% if (states.switch.meek_balcony.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'on' %} 20
        {% elif (states.switch.meek_balcony.state) == 'on' and (states.switch.mqtt_scene_goodnight.state) == 'off' %} 100
        {% else %}0
        {% endif %}
