- alias: "Switch - Wall On Off"
  trigger:
    - platform: state
      entity_id: switch.newkaku_0114ef92_b

  action:
    service: light.turn_on
    entity_id: light.livingroom_wall
    data_template:
      brightness_pct: "{{ 100 if is_state('switch.newkaku_0114ef92_b', 'on') else 0 }}"
      kelvin: 4700
