- alias: 'Scene - Nobody Home'
  trigger:

  - platform: state
    entity_id: group.group_family

  condition:
    - condition: state
      entity_id: group.group_family
      state: 'not_home' 

    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'off'

  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.scene_daylight

  - service: input_boolean.turn_off
    entity_id: 
      - input_boolean.scene_kodi
      - input_boolean.scene_tv
      - input_boolean.scene_iptv
      - input_boolean.scene_evening
      - input_boolean.scene_appletv
      - input_boolean.scene_sexy
      - input_boolean.lux_level_low

# TURN OFF ALL LIGHT
  - service: script.nobody_home
