###########################################################################################
#
# SCENE GOODNIGHT WHEN WE GONNA SLEEP
#
###########################################################################################

- alias: "Scene - Goodnight"
  trigger:

    platform: state
    entity_id: switch.mqtt_scene_goodnight
    to: "on"

  action:
    - service: homeassistant.turn_off
      entity_id: group.circadian_lights

    - service: switch.turn_off
      data:
        entity_id:
          - switch.mqtt_lux_level_low
          - switch.mqtt_disable_nest_control
          - switch.circadian_lighting_circadian_bedroom

    - service: switch.turn_off
      data:
        entity_id:
          - switch.mqtt_scene_appletv
          - switch.mqtt_scene_cooking
          - switch.mqtt_scene_daytime
          - switch.mqtt_scene_disco
          - switch.mqtt_scene_evening
          - switch.mqtt_scene_guests
          - switch.mqtt_scene_sexy
          - switch.mqtt_scene_sleeping
          - switch.mqtt_scene_tv

    - service: remote.turn_off
      entity_id: remote.logitech_harmony

    - delay: 00:00:01

    - service: homeassistant.turn_on
      data_template:
        entity_id: light.newkaku_01401eb6_a
        brightness_pct: >-
          {% if states('binary_sensor.node_21') == 'on' and states('switch.mqtt_kay_learning') == 'on' %} 100
          {% else %} 0
          {% endif %}

    - service: light.turn_off
      entity_id: light.nanoleaf

    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_all
        brightness_pct: "{{ 50 if is_state('binary_sensor.node_12', 'on') else 100 }}"

    - service: light.turn_on
      data:
        entity_id: light.bathroom_all
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id:
          - light.hallway
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
          - light.dressoir_all
          - light.livingroom_all
        brightness_pct: 20

    - delay: 00:00:02

    - service: light.turn_off
      data:
        entity_id:
          - light.hallway
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
          - light.dressoir_all
          - light.livingroom_all
          - light.balcony

    - service_template: input_number.set_value
      data_template:
        entity_id: input_number.fullykiosk_brightness_slider
        value: 1

    - service: light.turn_off
      entity_id: light.browser_321be4fb_d450a466

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_scene_goodnight: "true"
