###########################################################################################
#
# SCENE FOR APPLE TV WHEN SUN IS BELOW HORIZON
#
###########################################################################################

- alias: "Scene - AppleTV"
  trigger:

    - platform: state
      entity_id: sun.sun

    - platform: state
      entity_id: sensor.harmony
      to: "apple_tv"

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: switch.mqtt_scene_appletv
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

    - condition: state
      entity_id: sensor.harmony
      state: "apple_tv"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

  action:
    - service: switch.turn_on
      entity_id: switch.mqtt_scene_appletv

    - service: input_boolean.turn_off
      data:
        entity_id:
          - input_boolean.lux_level_low

    - service: switch.turn_off
      data:
        entity_id:
          - switch.mqtt_scene_cooking
          - switch.mqtt_scene_daytime
          - switch.mqtt_scene_disco
          - switch.mqtt_scene_evening
          - switch.mqtt_scene_goodnight
          - switch.mqtt_scene_guests
          - switch.mqtt_scene_kodi
          - switch.mqtt_scene_sexy
          - switch.mqtt_scene_sleeping
          - switch.mqtt_scene_tv

    - service: light.turn_on
      data_template:
        entity_id: light.nanoleaf
        brightness_pct: 20
        effect: >-
          {% if (states.sensor.holiday.state) == 'Christmas' %} Christmas
          {% elif (states.sensor.holiday.state) == 'Halloween' %} Halloween
          {% elif (states.sensor.holiday.state) == 'Kingsday' %} Kingsday
          {% elif (states.sensor.holiday.state) == 'Birthday' %} Kingsday
          {% else %} Kay
          {% endif %}

    - service_template: >-
         {% if (states.sensor.holiday.state) == 'Christmas' %} script.appletv_christmas
         {% elif (states.sensor.holiday.state) == 'Halloween' %} script.appletv_halloween
         {% elif (states.sensor.holiday.state) == 'Kingsday' %} script.appletv_kingsday
         {% elif (states.sensor.holiday.state) == 'Birthday' %} script.appletv_birthday
         {% else %} script.evening_normal
         {% endif %}

    - service: homeassistant.turn_on
      data_template:
        entity_id: light.newkaku_01401eb6_a
        brightness_pct: >-
          {% if (states.binary_sensor.node_21.state) == 'on' and (states.switch.mqtt_kay_learning.state) == 'on' %} 100
          {% elif (states.binary_sensor.node_21.state) == 'on' and (states.switch.mqtt_kay_learning.state) == 'off' %} 0
          {% elif (states.binary_sensor.node_21.state) == 'off' and (states.switch.mqtt_kay_learning.state) == 'on' %} 100
          {% else %} 50
          {% endif %}

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_scene_appletv: "true"
