- alias: 'Scene - 20Min before sunset'
  trigger:

    platform: sun
    event: sunset
    offset: '-00:18:00'

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'on'

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: 'on'

  action:
  - service: light.turn_on
    entity_id: light.nanoleaf
    data:
      brightness_pct: 30
      effect: 20MinSunset
