- alias: "Scene - Sexy"
  trigger:
    
    platform: state
    entity_id: input_boolean.scene_sexy
    to: "on"

  action:
    - service: light.turn_on
      entity_id: light.nanoleaf
      data:
        brightness_pct: 30
        effect: Romantic

    - service: light.turn_on
      data:
        entity_id: 
          - light.dressoir_all
          - light.livingroom_all
          - light.hallway
          - light.balcony
        color_name: red
        brightness_pct: 50
