- alias: "Scene - Sleeping"
  trigger:

    platform: state
    entity_id: input_boolean.scene_sleeping
    to: "on"

  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_all
        brightness_pct: 1
        transition: "10"
        
    - delay: "00:00:10"
        
    - service: light.turn_off
      entity_id: light.bedroom_all

    - service: light.turn_on
      data:
        entity_id: light.bedroom_5
        brightness_pct: 1
        effect: 0

    - delay:
        milliseconds: 300

    - service: light.turn_on
      data:
        entity_id: light.bedroom_6
        brightness_pct: 1
        effect: 0 

    - service: input_boolean.turn_off
      entity_id: input_boolean.scene_sleeping
      
    - service: switch.turn_off
      entity_id: switch.newkaku_01616a32_a

    - delay: "00:06:00"

    - service: light.turn_off
      data:
        entity_id:
          - light.bedroom_5
          - light.bedroom_6
