###########################################################################################
# SCENE FOR KODI WHEN SUN BELOW HORIZON TURN LIGHTS ON BASED ON STATUS KODI
###########################################################################################

- alias: "Scene - Kodi"
  trigger:

    - platform: state
      entity_id: sun.sun

    - entity_id: sensor.harmony
      platform: state
      to: "kodi"

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: switch.mqtt_scene_kodi
      state: "off"

    - condition: state
      entity_id: switch.mqtt_scene_goodnight
      state: "off"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

    - condition: state
      entity_id: sensor.harmony
      state: "kodi"

  action:
    - service: light.turn_on
      data:
        entity_id: light.browser_ae1b43e7_eb57c683
        brightness_pct: 50

    - service: switch.turn_on
      entity_id: switch.mqtt_scene_kodi

    - service: switch.turn_off
      data:
        entity_id:
          - switch.mqtt_scene_appletv
          - switch.mqtt_scene_cooking
          - switch.mqtt_scene_daytime
          - switch.mqtt_scene_disco
          - switch.mqtt_scene_evening
          - switch.mqtt_scene_goodnight
          - switch.mqtt_scene_guests
          - switch.mqtt_scene_sexy
          - switch.mqtt_scene_sleeping
          - switch.mqtt_scene_tv
          - switch.mqtt_lux_level_low

    - service: light.turn_on
      data_template:
        entity_id: light.nanoleaf
        brightness_pct: 30
        effect: >-
          {% if states('sensor.holiday') == 'Christmas' %} Christmas
          {% elif states('sensor.holiday') == 'Halloween' %} Halloween
          {% elif states('sensor.holiday') == 'Kingsday' %} Kingsday
          {% elif states('sensor.holiday') == 'Birthday' %} Kingsday
          {% else %} Kay
          {% endif %}

    - service_template: >-
         {% if states('sensor.holiday') == 'Christmas' %} script.kodi_christmas
         {% elif states('sensor.holiday') == 'Halloween' %} script.kodi_halloween
         {% elif states('sensor.holiday') == 'Kingsday' %} script.kodi_kingsday
         {% elif states('sensor.holiday') == 'Birthday' %} script.kodi_birthday
         {% else %} script.kodi_normal
         {% endif %}

    - service: homeassistant.turn_on
      data_template:
        entity_id: light.newkaku_01401eb6_a
        brightness_pct: >-
          {% if states('binary_sensor.neo_diningroomdoor_custom_sensor') == 'on' and states('switch.mqtt_kay_learning') == 'on' %} 100
          {% elif states('binary_sensor.neo_diningroomdoor_custom_sensor') == 'off' and states('switch.mqtt_kay_learning') == 'on' %} 100
          {% else %} 0
          {% endif %}

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_scene_kodi: "true"
