###########################################################################################
# SCENE GUESTS TURN OFF SOME AUTOMATIONS
###########################################################################################

- alias: "Scene - Guests"
  trigger:

    platform: state
    entity_id: switch.mqtt_scene_guests

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ 'Scene Guests is activated' if is_state('switch.mqtt_scene_guests', 'on') else 'Scene Guests is deactivated' }}"
        priority: 0
        sound: bike
        title: "HA Scene System"
