- alias: 'Scene - Guests'
  trigger:

  - entity_id: input_boolean.scene_guests
    platform: state

  action:
    - service: script.pushover_engine
      data_template:
        message: "{{ 'Scene Guests is activated' if is_state('input_boolean.scene_guests', 'on') else 'Scene Guests is deactivated' }}"
        priority: 0
        sound: bike
        title: "HA Scene System"

    - service_template: "{{ 'automation.turn_off' if is_state('input_boolean.scene_guests', 'on') else 'automation.turn_on' }}"
      data:
        entity_id: 
          - automation.motion_detection_livingroom_on_off
          - automation.motion_detection_diningroom_on_off
          - automation.motion_detection_hallway_on_off
