###########################################################################################
#
# SCENE NOBODY HOME TURN OFF EVERYTHING THATS NOT NEEDED WHEN WE NOT THERE
#
###########################################################################################

- alias: "Scene - Nobody Home"
  trigger:

    platform: state
    entity_id: binary_sensor.sensor_manual_family_home
    to: "off"

  action:
    - service: light.turn_on
      data:
        entity_id: light.browser_ae1b43e7_eb57c683
        brightness_pct: 10

    - service: switch.turn_on
      entity_id: switch.mqtt_scene_daytime

    - service: switch.turn_off
      data:
        entity_id:
          - switch.mqtt_scene_appletv
          - switch.mqtt_scene_cooking
          - switch.mqtt_scene_disco
          - switch.mqtt_scene_evening
          - switch.mqtt_scene_goodnight
          - switch.mqtt_scene_guests
          - switch.mqtt_scene_kodi
          - switch.mqtt_scene_sexy
          - switch.mqtt_scene_sleeping
          - switch.mqtt_scene_tv
          - switch.mqtt_lux_level_low

    - service: light.turn_off
      data:
        entity_id:
          - light.livingroom_all
          - light.dressoir_all
          - light.kitchen_all
          - light.sink_all
          - light.livingroom_all
          - light.bedroom_all
          - light.bathroom_all
          - light.hallway
          - light.balcony
          - light.toilet_all
          - light.nanoleaf
          - light.newkaku_01401eb6_a

    - service: remote.turn_off
      entity_id: remote.logitech_harmony

    - service: fan.turn_off
      entity_id: fan.afzuiging_badkamer
