- alias: "Scene - Kay Learning"
  trigger:

  - entity_id: switch.kay_learning
    platform: state

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: "off"

  action:
  - service: light.turn_on
    entity_id: light.newkaku_01401eb6_a
    data_template:
      brightness_pct: "{{ 100 if is_state('switch.kay_learning', 'on') else 50 }}"
