- alias: 'Control - Kay Learning On or Off'
  trigger:

  - entity_id: switch.kay_learning
    platform: state

  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'off'

  action:
  - service: light.turn_on
    data_template:
      entity_id: light.newkaku_01401eb6_a
      brightness_pct: >-
       {% if (states.switch.kay_learning.state) == 'on' %} 100
       {% else %} 50
       {% endif %}

  - service: notify.pushover
    data_template:
      message: >-
       {% if (states.switch.kay_learning.state) == 'on' %} Kay learning is activated.
       {% else %} Kay learning is deactivated.
       {% endif %}
      title: "HA System"
