###########################################################################################
#
# SCENE FOR COOKING TURN ON LIGHTS KITCHEN BRIGHTNESS 100%
#
###########################################################################################

- alias: "Scene - Cooking"
  trigger:

    platform: state
    entity_id: switch.mqtt_scene_cooking

  condition:
    condition: state
    entity_id: switch.mqtt_scene_goodnight
    state: "off"

  action:
    service: light.turn_on
    data_template:
      entity_id:
        - light.sink_all
        - light.kitchen_all
      kelvin: 2800
      brightness_pct: "{{ 100 if is_state('switch.mqtt_scene_cooking', 'on') else 0 }}"
