###########################################################################################
#
# SCENE FOR KODI WHEN SUN BELOW HORIZON TURN LIGHTS ON BASED ON STATUS KODI
#
###########################################################################################

- alias: "Scene - Kodi"
  trigger:

    - platform: state
      entity_id: sun.sun

    - entity_id: sensor.harmony
      platform: state
      to: "kodi"

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: input_boolean.scene_kodi
      state: "off"

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: "off"

    - condition: state
      entity_id: sensor.harmony
      state: "kodi"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.scene_kodi

    - service: input_boolean.turn_off
      data:
        entity_id:
          - input_boolean.scene_evening
          - input_boolean.scene_tv
          - input_boolean.scene_daylight
          - input_boolean.scene_appletv
          - input_boolean.scene_sexy
          - input_boolean.lux_level_low

        - service: switch.turn_off
          data:
            entity_id:
          - switch.mqtt_scene_appletv
          - switch.mqtt_scene_cooking
          - switch.mqtt_scene_daytime
          - switch.mqtt_scene_disco
          - switch.mqtt_scene_evening
          - switch.mqtt_scene_goodnight
          - switch.mqtt_scene_guests
          - switch.mqtt_scene_sexy
          - switch.mqtt_scene_sleeping
          - switch.mqtt_scene_tv

    - service: light.turn_on
      data_template:
        entity_id: light.nanoleaf
        brightness_pct: 30
        effect: >-
          {% if (states.sensor.holiday.state) == 'Christmas' %} Christmas
          {% elif (states.sensor.holiday.state) == 'Halloween' %} Halloween
          {% elif (states.sensor.holiday.state) == 'Kingsday' %} Kingsday
          {% elif (states.sensor.holiday.state) == 'Birthday' %} Kingsday
          {% else %} Kay
          {% endif %}

    - service_template: >-
         {% if (states.sensor.holiday.state) == 'Christmas' %} script.kodi_christmas
         {% elif (states.sensor.holiday.state) == 'Halloween' %} script.kodi_halloween
         {% elif (states.sensor.holiday.state) == 'Kingsday' %} script.kodi_kingsday
         {% elif (states.sensor.holiday.state) == 'Birthday' %} script.kodi_birthday
         {% else %} script.evening_normal
         {% endif %}

    - service: homeassistant.turn_on
      data_template:
        entity_id: light.newkaku_01401eb6_a
        brightness_pct: >-
          {% if (states.binary_sensor.node_21.state) == 'on' and (states.switch.kay_learning.state) == 'on' %} 100
          {% elif (states.binary_sensor.node_21.state) == 'off' and (states.switch.kay_learning.state) == 'on' %} 100
          {% else %} 0
          {% endif %}

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_scene_kodi: "true"
