- alias: 'Scene - Evening'
  trigger:

  - platform: time_pattern
    minutes: "/1"

  - platform: state
    entity_id: sun.sun

  - platform: state
    entity_id: binary_sensor.sensor_manual_family_home

  - entity_id: sensor.harmony
    platform: state
    to: 'Off'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - condition: state
      entity_id: input_boolean.scene_evening
      state: 'off'

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: 'off'

    - condition: state
      entity_id: sensor.harmony
      state: 'Off'

    - condition: state 
      entity_id: binary_sensor.sensor_manual_family_home
      state: 'on'

  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.scene_evening

  - service: input_boolean.turn_off
    data:
      entity_id:
        - input_boolean.scene_kodi
        - input_boolean.scene_tv
        - input_boolean.scene_daylight
        - input_boolean.scene_appletv
        - input_boolean.scene_sexy
        - input_boolean.lux_level_low

  - service: light.turn_on
    entity_id: light.nanoleaf
    data_template:
      brightness_pct: 30
      effect: >-
        {% if (states.sensor.holiday.state) == 'Christmas' %} Christmas
        {% elif (states.sensor.holiday.state) == 'Halloween' %} Halloween
        {% elif (states.sensor.holiday.state) == 'Kingsday' %} Kingsday
        {% elif (states.sensor.holiday.state) == 'Birthday' %} Kingsday
        {% else %} Kay
        {% endif %}

  - service_template: >- 
       {% if (states.sensor.holiday.state) == 'Christmas' %} script.evening_christmas
       {% elif (states.sensor.holiday.state) == 'Halloween' %} script.evening_halloween
       {% elif (states.sensor.holiday.state) == 'Kingsday' %} script.evening_kingsday
       {% elif (states.sensor.holiday.state) == 'Birthday' %} script.evening_birthday
       {% else %} script.evening_normal
       {% endif %}

  - service: homeassistant.turn_on
    data_template:
      entity_id: light.newkaku_01401eb6_a
      brightness_pct: >-
        {% if (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'on' %} 100
        {% elif (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'off' %} 0
        {% elif (states.binary_sensor.node_10.state) == 'off' and (states.switch.kay_learning.state) == 'on' %} 100 
        {% else %} 50
        {% endif %}

  - service: script.engine_say
    data_template:
      media_player: media_player.this_device
      say_scene_evening: "true"
