- alias: 'Scene - Daylight Someone Home'
  trigger:

  - platform: time_pattern
    minutes: "/1" 

  - platform: state
    entity_id: sun.sun

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

    - condition: state
      entity_id: input_boolean.scene_daylight
      state: 'off'

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: 'on' 

  action:
  - service: shell_command.meek_toilet_nightscene_off
  
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.scene_daylight

  - service: input_boolean.turn_off
    data:
      entity_id: 
        - input_boolean.scene_goodnight
        - input_boolean.scene_kodi
        - input_boolean.scene_tv
        - input_boolean.scene_evening
        - input_boolean.scene_appletv
        - input_boolean.scene_sexy
        - input_boolean.lux_level_low

  - service: light.turn_off
    data:
      entity_id:
        - light.livingroom_all
        - light.dressoir_all
        - light.kitchen_all
        - light.sink_all
        - light.livingroom_all
        - light.hallway
        - light.balcony
        - light.toilet_all
        - light.nanoleaf
        - light.newkaku_01401eb6_a
        
  - service: switch.turn_off
    entity_id:
      - switch.node_8_switch
      - switch.node_21_switch
      - switch.node_22_switch

  - service_template: "{{ 'light.turn_on' if is_state('binary_sensor.node_14', 'on') else 'light.turn_off' }}"
    data:
      entity_id:
        - light.bathroom_all
