- alias: "Scene - Goodnight"
  trigger:
    
    platform: state
    entity_id: input_boolean.scene_goodnight
    to: "on"

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: input_boolean.scene_goodnight
      state: "on"

  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.scene_kodi
          - input_boolean.scene_tv
          - input_boolean.scene_daylight
          - input_boolean.scene_appletv
          - input_boolean.scene_sexy
          - input_boolean.scene_evening
          - input_boolean.lux_level_low
          - input_boolean.nest_disable_control
          - input_boolean.lux_level_low

    - service: remote.turn_off
      entity_id: remote.logitech_harmony

    - service: homeassistant.turn_on
      data_template:
        entity_id: light.newkaku_01401eb6_a
        brightness_pct: >-
          {% if (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'on' %} 100
          {% else %} 0
          {% endif %}

    - service: light.turn_off
      entity_id: light.nanoleaf

    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_all
        kelvin: 2800
        brightness_pct: "{{ 50 if is_state('binary_sensor.node_12', 'on') else 100 }}"

    - service: light.turn_on
      data:
        entity_id: light.bathroom_all
        kelvin: 2800
        brightness_pct: 100

    - service: light.turn_on
      data:
        entity_id:
          - light.hallway
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
          - light.dressoir_all
          - light.livingroom_all
        kelvin: 2800
        brightness_pct: 20

    - delay: 00:00:02

    - service: light.turn_off
      data:
        entity_id:
          - light.hallway
          - light.kitchen_all
          - light.sink_all
          - light.toilet_all
          - light.dressoir_all
          - light.livingroom_all
          - light.balcony 

    - service_template: input_number.set_value
      data_template:
        entity_id: input_number.fullykiosk_brightness_slider
        value: 1
    
    - service: light.turn_off
      entity_id: light.lenovo_full_kiosk

# Christmass switches        
#    - service: switch.turn_off
#      entity_id:
#        - switch.node_8_switch
#        - switch.node_21_switch
#        - switch.node_22_switch
#        - switch.node_2_switch 
#  - service: shell_command.meek_toilet_nightscene_on

    - service: script.engine_say
      data_template:
        media_player: media_player.this_device
        say_scene_goodnight: "true"
