###########################################################################################
#
# SCENE DISCO WHEN THERE IS A PARTY OUR HOUSE IS A DISCOBALL
#
###########################################################################################

- alias: "Scene - Disco"
  trigger:

    platform: state
    entity_id: input_boolean.scene_disco
    to: "on"

  action:
    - service: light.turn_on
      data:
        entity_id: light.nanoleaf
        brightness_pct: 30
        effect: NorthernLight

    - service: light.turn_on
      data:
        entity_id: light.dressoir_1
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.dressoir_2
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.dressoir_3
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.livingroom_1
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.livingroom_2
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.livingroom_3
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.livingroom_4
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.balcony
        effect: 0
        brightness_pct: 100

    - delay:
        milliseconds: 200

    - service: light.turn_on
      data:
        entity_id: light.hallway
        effect: 0
        brightness_pct: 100
