- alias: "Scene - 20Min before sunset"
  trigger:

    platform: sun
    event: sunset
    offset: "-00:18:00"
  condition:
    - condition: state
      entity_id: input_boolean.scene_daylight
      state: "on"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

  action:
  - service: light.turn_on
    entity_id: light.nanoleaf
    data_template:
      brightness_pct: 30
      effect: "{{ 'Christmas' if is_state('sensor.holiday', 'Christmas') else '20MinSunset' }}"

  - service: script.engine_say
    data_template:
      media_player: media_player.this_device
      say_scene_sunset: "true"
