###########################################################################################
#
# SCENE FOR DAYTIME WHEN SUN IS ABOVE HORIZON TURN OFF EVERYTHING THATS NOT NEEDED AT DAYTIME
#
###########################################################################################

- alias: "Scene - Daylight Someone Home"
  trigger:

    - platform: time_pattern
      minutes: "/1"

    - platform: state
      entity_id: sun.sun

  condition:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"

    - condition: state
      entity_id: switch.mqtt_scene_daytime
      state: "off"

    - condition: state
      entity_id: binary_sensor.sensor_manual_family_home
      state: "on"

  action:
    - service: switch.turn_on
      entity_id: switch.mqtt_scene_daytime

    - service: light.turn_on
      data:
        entity_id: light.browser_ae1b43e7_eb57c683
        brightness_pct: 75

    - service: switch.turn_off
      data:
        entity_id:
          - switch.mqtt_scene_appletv
          - switch.mqtt_scene_cooking
          - switch.mqtt_scene_disco
          - switch.mqtt_scene_evening
          - switch.mqtt_scene_goodnight
          - switch.mqtt_scene_guests
          - switch.mqtt_scene_kodi
          - switch.mqtt_scene_sexy
          - switch.mqtt_scene_sleeping
          - switch.mqtt_scene_tv
          - switch.mqtt_lux_level_low

    - service: light.turn_off
      data:
        entity_id:
          - light.livingroom_all
          - light.dressoir_all
          - light.kitchen_all
          - light.sink_all
          - light.livingroom_all
          - light.hallway
          - light.balcony
          - light.toilet_all
          - light.nanoleaf
          - light.newkaku_01401eb6_a

    - service_template: input_number.set_value
      data_template:
        entity_id: input_number.fullykiosk_brightness_slider
        value: 100

    - service_template: "{{ 'light.turn_on' if is_state('binary_sensor.node_15', 'on') else 'light.turn_off' }}"
      entity_id: light.bathroom_all

    - service: script.pushover_engine
      data_template:
        message: "HA - Scene Daytime activated"
        priority: 0
        sound: bike
        title: "HA System"
