- alias: 'Scene - Guests'
  trigger:

  - entity_id: input_boolean.scene_guests
    platform: state

  action:
  - service: notify.pushover
    data_template:
      message: >-
        {% if (states.input_boolean.scene_guests.state) == 'on' %} "Scene Guests is activated"
        {% else %} "Scene Guests is deactivated"
        {% endif %}
      title: "HA Scene System"

  - service_template: >-
      {% if (states.input_boolean.scene_guests.state) == 'on' %} automation.turn_off
      {% else %} automation.turn_on
      {% endif %}
    entity_id: 
      - automation.motion_detection_livingroom_on_off
      - automation.motion_detection_diningroom_on_off
      - automation.motion_detection_hallway_on_off
