- alias: "Scene - Kay Learning"
  trigger:

    platform: state
    entity_id: switch.kay_learning

  condition:
    condition: state
    entity_id: input_boolean.scene_daylight
    state: "off"

  action:
    service: light.turn_on
    data_template:
      entity_id: light.newkaku_01401eb6_a
      brightness_pct: "{{ 100 if is_state('switch.kay_learning', 'on') else 50 }}"
