esphome:
  name: meektest
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
      then:
        - light.toggle: light.dressoir_1

wifi:
  ssid: "Oudenes.Photography"
  password: "Abercrombie1977"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Meektest Fallback Hotspot"
    password: "ByW7Io8ZJoU2"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
