- alias: Switch - Balcony On
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fdd46_b
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.balcony
    data:
      brightness_pct: 100
      kelvin: 2700

- alias: Switch - Balcony Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_011fdd46_b
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.balcony
