- alias: Switch - Bathroom On Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_01616a32_a

  action:
    service: light.turn_on
    entity_id: light.bathroom_all
    data_template:
      brightness_pct: >-
        {% if (states.switch.newkaku_01616a32_a.state) == 'on' %} 100
        {% else %} 0
        {% endif %}
      kelvin: 4700
