- alias: Switch - Bedroom On
  trigger:
    - platform: state
      entity_id: switch.newkaku_01074522_a
      to: 'on'

  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_all
      brightness_pct: "{{ 20 if is_state('binary_sensor.node_12', 'on') else 100 }}"
      kelvin: 4700

- alias: Switch - Bedroom Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_01074522_a
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.bedroom_all
