- alias: Switch - Dining Table On
  trigger:
    - platform: state
      entity_id: light.newkaku_01401eb6_a
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.newkaku_01401eb6_a
    data_template:
      brightness_pct: >
        {% if (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'on' %} 100
        {% elif (states.binary_sensor.node_10.state) == 'on' and (states.switch.kay_learning.state) == 'off' %} 0
        {% elif (states.binary_sensor.node_10.state) == 'off' and (states.switch.kay_learning.state) == 'on' %} 100
        {% else %} 20
        {% endif %}


- alias: Switch - Dining Table Off
  trigger:
    - platform: state
      entity_id: light.newkaku_01401eb6_a
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.newkaku_01401eb6_a
