- alias: Switch - Dining Table On Off
  trigger:
    - platform: state
      entity_id: light.newkaku_01401eb6_a
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.newkaku_01401eb6_a
    data_template:
      brightness_pct: >
        {% if (states.switch.kay_learning.state) == 'on' %} 100
        {% else %} 20
        {% endif %}
