- alias: Switch - Toilet On Off
  trigger:
    - platform: state
      entity_id: switch.newkaku_016138ba_a

  action:
    service: light.turn_on
    entity_id: light.hallway
    data_template:
      brightness_pct: >-
        {% if (states.switch.newkaku_016138ba_a.state) == 'on' %} 100
        {% else %} 0
        {% endif %}
      kelvin: 2700
